window.dhtmlx||(dhtmlx={});dhtmlx.version="3.0";dhtmlx.codebase="./";dhtmlx.extend=function(a,b){for(var c in b)a[c]=b[c];b.j&&a.j();return a};
dhtmlx.proto_extend=function(){for(var a=arguments,b=a[0],c=[],d=a.length-1;d>0;d--){if(typeof a[d]=="function")a[d]=a[d].prototype;for(var e in a[d])if(e=="_init")c.push(a[d][e]);else b[e]||(b[e]=a[d][e])}a[0].j&&c.push(a[0].j);b.j=function(){for(var g=0;g<c.length;g++)c[g].apply(this,arguments)};b.base=a[1];var f=function(g){this.j(g);this.K&&this.K(g,this.defaults)};f.prototype=b;b=a=null;return f};dhtmlx.bind=function(a,b){return function(){return a.apply(b,arguments)}};
dhtmlx.require=function(a){if(!dhtmlx.X[a]){dhtmlx.exec(dhtmlx.ajax().sync().get(dhtmlx.codebase+a).responseText);dhtmlx.X[a]=true}};dhtmlx.X={};dhtmlx.exec=function(a){window.execScript?window.execScript(a):window.eval(a)};dhtmlx.methodPush=function(a,b){return function(){var c=false;return c=a[b].apply(a,arguments)}};dhtmlx.isNotDefined=function(a){return typeof a=="undefined"};dhtmlx.delay=function(a,b,c,d){setTimeout(function(){var e=a.apply(b,c);a=b=c=null;return e},d||1)};
dhtmlx.uid=function(){if(!this.ta)this.ta=(new Date).valueOf();this.ta++;return this.ta};dhtmlx.toNode=function(a){if(typeof a=="string")return document.getElementById(a);return a};dhtmlx.toArray=function(a){return dhtmlx.extend(a||[],dhtmlx.PowerArray)};dhtmlx.toFunctor=function(a){return typeof a=="string"?eval(a):a};dhtmlx.n={};
dhtmlx.event=function(a,b,c,d){a=dhtmlx.toNode(a);var e=dhtmlx.uid();dhtmlx.n[e]=[a,b,c];if(d)c=dhtmlx.bind(c,d);if(a.addEventListener)a.addEventListener(b,c,false);else a.attachEvent&&a.attachEvent("on"+b,c);return e};dhtmlx.eventRemove=function(a){if(a){var b=dhtmlx.n[a];if(b[0].removeEventListener)b[0].removeEventListener(b[1],b[2],false);else b[0].detachEvent&&b[0].detachEvent("on"+b[1],b[2]);delete this.n[a]}};
dhtmlx.EventSystem={j:function(){this.n={};this.Q={};this.J={}},block:function(){this.n.ya=true},unblock:function(){this.n.ya=false},mapEvent:function(a){dhtmlx.extend(this.J,a)},callEvent:function(a,b){if(this.n.ya)return true;a=a.toLowerCase();var c=this.n[a.toLowerCase()],d=true;if(c)for(var e=0;e<c.length;e++)if(c[e].apply(this,b||[])===false)d=false;if(this.J[a]&&!this.J[a].callEvent(a,b))d=false;return d},attachEvent:function(a,b,c){a=a.toLowerCase();c=c||dhtmlx.uid();b=dhtmlx.toFunctor(b);
var d=this.n[a]||dhtmlx.toArray();d.push(b);this.n[a]=d;this.Q[c]={f:b,t:a};return c},detachEvent:function(a){var b=this.Q[a].t,c=this.Q[a].f;b=this.n[b];b.remove(c);delete this.Q[a]}};
dhtmlx.PowerArray={removeAt:function(a,b){if(a>=0)this.splice(a,b||1)},remove:function(a){this.removeAt(this.find(a))},insertAt:function(a,b){if(!b&&b!==0)this.push(a);else{var c=this.splice(b,this.length-b);this[b]=a;this.push.apply(this,c)}},find:function(a){for(i=0;i<this.length;i++)if(a==this[i])return i;return-1},each:function(a,b){for(var c=0;c<this.length;c++)a.call(b||this,this[c])},map:function(a,b){for(var c=0;c<this.length;c++)this[c]=a.call(b||this,this[c]);return this}};dhtmlx.env={};
if(navigator.userAgent.indexOf("Opera")!=-1)dhtmlx.Db=true;else{dhtmlx.H=!!document.all;dhtmlx.Pa=!document.all;dhtmlx.Eb=navigator.userAgent.indexOf("KHTML")!=-1;if(navigator.appVersion.indexOf("MSIE 8.0")!=-1&&document.compatMode!="BackCompat")dhtmlx.H=8}dhtmlx.env={};
(function(){dhtmlx.env.transform=false;dhtmlx.env.transition=false;var a={};a.names=["transform","transition"];a.transform=["transform","WebkitTransform","MozTransform","oTransform"];a.transition=["transition","WebkitTransition","MozTransition","oTransition"];for(var b=document.createElement("DIV"),c=0;c<a.names.length;c++)for(;p=a[a.names[c]].pop();)if(typeof b.style[p]!="undefined")dhtmlx.env[a.names[c]]=true})();
dhtmlx.env.transform_prefix=function(){var a;if(dhtmlx.Db)a="-o-";else{a="";if(dhtmlx.Pa)a="-moz-";if(dhtmlx.Eb)a="-webkit-"}return a}();dhtmlx.env.svg=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")}();dhtmlx.zIndex={drag:1E4};
dhtmlx.html={create:function(a,b,c){b=b||{};var d=document.createElement(a);for(var e in b)d.setAttribute(e,b[e]);if(b.style)d.style.cssText=b.style;if(b["class"])d.className=b["class"];if(c)d.innerHTML=c;return d},getValue:function(a){a=dhtmlx.toNode(a);if(!a)return"";return dhtmlx.isNotDefined(a.value)?a.innerHTML:a.value},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else a&&a.parentNode&&a.parentNode.removeChild(a)},insertBefore:function(a,b,c){if(a)b?b.parentNode.insertBefore(a,
b):c.appendChild(a)},locate:function(a,b){a=a||event;for(var c=a.target||a.srcElement;c;){if(c.getAttribute){var d=c.getAttribute(b);if(d)return d}c=c.parentNode}return null},offset:function(a){if(a.getBoundingClientRect){var b=a.getBoundingClientRect(),c=document.body,d=document.documentElement,e=window.pageYOffset||d.scrollTop||c.scrollTop,f=window.pageXOffset||d.scrollLeft||c.scrollLeft,g=d.clientTop||c.clientTop||0,h=d.clientLeft||c.clientLeft||0,j=b.top+e-g,l=b.left+f-h;return{y:Math.round(j),
x:Math.round(l)}}else{for(l=j=0;a;){j+=parseInt(a.offsetTop,10);l+=parseInt(a.offsetLeft,10);a=a.offsetParent}return{y:j,x:l}}},pos:function(a){a=a||event;if(a.pageX||a.pageY)return{x:a.pageX,y:a.pageY};var b=dhtmlx.H&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:a.clientX+b.scrollLeft-b.clientLeft,y:a.clientY+b.scrollTop-b.clientTop}},preventEvent:function(a){a&&a.preventDefault&&a.preventDefault();dhtmlx.html.stopEvent(a)},stopEvent:function(a){(a||event).cancelBubble=
true;return false},addCss:function(a,b){a.className+=" "+b},removeCss:function(a,b){a.className=a.className.replace(RegExp(b,"g"),"")}};(function(){var a=document.getElementsByTagName("SCRIPT");if(a.length){a=(a[a.length-1].getAttribute("src")||"").split("/");a.splice(a.length-1,1);dhtmlx.codebase=a.slice(0,a.length).join("/")+"/"}})();dhtmlx.ui={};
dhtmlx.Template={da:{},empty:function(){return""},setter:function(a,b){return dhtmlx.Template.fromHTML(b)},obj_setter:function(a,b){var c=dhtmlx.Template.setter(a,b),d=this;return function(){return c.apply(d,arguments)}},fromHTML:function(a){if(typeof a=="function")return a;if(this.da[a])return this.da[a];a=(a||"").toString();a=a.replace(/[\r\n]+/g,"\\n");a=a.replace(/\{obj\.([^}?]+)\?([^:]*):([^}]*)\}/g,'"+(obj.$1?"$2":"$3")+"');a=a.replace(/\{common\.([^}\(]*)\}/g,'"+common.$1+"');a=a.replace(/\{common\.([^\}\(]*)\(\)\}/g,
'"+(common.$1?common.$1(obj):"")+"');a=a.replace(/\{obj\.([^}]*)\}/g,'"+obj.$1+"');a=a.replace(/#([a-z0-9_]+)#/gi,'"+obj.$1+"');a=a.replace(/\{obj\}/g,'"+obj+"');a=a.replace(/\{-obj/g,"{obj");a=a.replace(/\{-common/g,"{common");a='return "'+a+'";';return this.da[a]=Function("obj","common",a)}};
dhtmlx.Type={add:function(a,b){if(!a.types&&a.prototype.types)a=a.prototype;var c=b.name||"default";this.va(b);this.va(b,"edit");this.va(b,"loading");a.types[c]=dhtmlx.extend(dhtmlx.extend({},a.types[c]||this.kb),b);return c},kb:{css:"default",template:function(){return""},template_edit:function(){return""},template_loading:function(){return"..."},width:150,height:80,margin:5,padding:0},va:function(a,b){b="template"+(b?"_"+b:"");var c=a[b];if(c&&typeof c=="string"){if(c.indexOf("->")!=-1){c=c.split("->");
switch(c[0]){case "html":c=dhtmlx.html.getValue(c[1]).replace(/\"/g,'\\"');break;case "http":c=(new dhtmlx.ajax).sync().get(c[1],{uid:(new Date).valueOf()}).responseText;break;default:break}}a[b]=dhtmlx.Template.fromHTML(c)}}};
dhtmlx.Settings={j:function(){this.e=this.config={}},define:function(a,b){if(typeof a=="object")return this.Ya(a);return this.Da(a,b)},Da:function(a,b){var c=this[a+"_setter"];return this.e[a]=c?c.call(this,a,b):b},Ya:function(a){if(a)for(var b in a)this.Da(b,a[b])},K:function(a,b){var c=dhtmlx.extend({},b);typeof a=="object"&&!a.tagName&&dhtmlx.extend(c,a);this.Ya(c)},D:function(a,b){for(var c in b)switch(typeof a[c]){case "object":a[c]=this.D(a[c]||{},b[c]);break;case "undefined":a[c]=b[c];break;
default:break}return a},qa:function(a,b,c){if(typeof a=="object"&&!a.tagName)a=a.container;this.g=dhtmlx.toNode(a);if(!this.g&&c)this.g=c(a);this.g.className+=" "+b;this.g.onselectstart=function(){return false};this.h=this.g},Vb:function(a){if(typeof a=="object")return this.type_setter("type",a);this.type=dhtmlx.extend({},this.types[a]);this.customize()},customize:function(a){a&&dhtmlx.extend(this.type,a);this.type.Ra=dhtmlx.Template.fromHTML(this.template_item_start(this.type));this.type.Qa=this.template_item_end(this.type);
this.render()},type_setter:function(a,b){this.Vb(typeof b=="object"?dhtmlx.Type.add(this,b):b);return b},template_setter:function(a,b){return this.type_setter("type",{template:b})},css_setter:function(a,b){this.g.className+=" "+b;return b}};
dhtmlx.Destruction={j:function(){dhtmlx.destructors.push(this)},destructor:function(){this.destructor=function(){};this.C=this.k=null;this.q&&document.body.appendChild(this.q);this.q=null;if(this.g){this.g.innerHTML="";this.g.k=null}this.data=this.g=this.h=null;this.n=this.Q={}}};dhtmlx.destructors=[];
dhtmlx.event(window,"unload",function(){for(var a=0;a<dhtmlx.destructors.length;a++)dhtmlx.destructors[a].destructor();dhtmlx.destructors=[];for(var b in dhtmlx.n){a=dhtmlx.n[b];if(a[0].removeEventListener)a[0].removeEventListener(a[1],a[2],false);else a[0].detachEvent&&a[0].detachEvent("on"+a[1],a[2]);delete dhtmlx.n[b]}});
dhtmlx.ui.pager=function(a){this.name="Pager";dhtmlx.extend(this,dhtmlx.Settings);this.qa(a,"dhx_pager");dhtmlx.extend(this,dhtmlx.EventSystem);dhtmlx.extend(this,dhtmlx.SingleRender);dhtmlx.extend(this,dhtmlx.MouseEvents);this.K(a,{size:10,page:-1,group:5,count:0,type:"default"});this.data=this.e;this.refresh()};
dhtmlx.ui.pager.prototype={r:"dhx_p_id",on_click:{dhx_pager_item:function(a,b){this.select(b)}},select:function(a){switch(a){case "next":a=this.e.page+1;break;case "prev":a=this.e.page-1;break;case "first":a=0;break;case "last":a=this.e.limit-1;break;default:break}if(a<0)a=0;if(a>=this.data.limit)a=this.data.limit-1;if(this.callEvent("onBeforePageChange",[this.e.page,a])){this.data.page=a*1;this.refresh();this.callEvent("onAfterPageChange",[a])}},types:{"default":{template:dhtmlx.Template.fromHTML("{common.pages()}"),
pages:function(a){var b="";if(a.page==-1)return"";a.min=a.page-Math.round((a.group-1)/2);a.max=a.min+a.group-1;if(a.min<0){a.max+=a.min*-1;a.min=0}if(a.max>=a.limit){a.min-=Math.min(a.min,a.max-a.limit+1);a.max=a.limit-1}for(var c=a.min||0;c<=a.max;c++)b+=this.button({id:c,index:c+1,selected:c==a.page?"_selected":""});return b},page:function(a){return a.page+1},first:function(){return this.button({id:"first",index:" &lt;&lt; ",selected:""})},last:function(){return this.button({id:"last",index:" &gt;&gt; ",
selected:""})},prev:function(){return this.button({id:"prev",index:"&lt;",selected:""})},next:function(){return this.button({id:"next",index:"&gt;",selected:""})},button:dhtmlx.Template.fromHTML("<div dhx_p_id='{obj.id}' class='dhx_pager_item{obj.selected}'>{obj.index}</div>")}},refresh:function(){var a=this.e;a.limit=Math.ceil(a.count/a.size);if(a.limit&&a.limit!=a.old_limit)a.page=Math.min(a.limit-1,a.page);var b=a.page;if(b!=-1&&b!=a.old_page||a.limit!=a.old_limit){this.render();this.callEvent("onRefresh",
[]);a.old_limit=a.limit;a.old_page=a.page}},template_item_start:dhtmlx.Template.fromHTML("<div>"),template_item_end:dhtmlx.Template.fromHTML("</div>")};dhtmlx.SingleRender={j:function(){},M:function(a){return this.type.Ra(a,this.type)+this.type.template(a,this.type)+this.type.Qa},render:function(){if(!this.callEvent||this.callEvent("onBeforeRender",[this.data])){if(this.data)this.h.innerHTML=this.M(this.data);this.callEvent&&this.callEvent("onAfterRender",[])}}};
dhtmlx.ui.Tooltip=function(a){this.name="Tooltip";this.version="3.0";if(typeof a=="string")a={template:a};dhtmlx.extend(this,dhtmlx.Settings);dhtmlx.extend(this,dhtmlx.SingleRender);this.K(a,{type:"default",dy:0,dx:20});this.h=this.g=document.createElement("DIV");this.g.className="dhx_tooltip";dhtmlx.html.insertBefore(this.g,document.body.firstChild)};
dhtmlx.ui.Tooltip.prototype={show:function(a,b){if(!this.Ea){if(this.data!=a){this.data=a;this.render(a)}this.g.style.top=b.y+this.e.dy+"px";this.g.style.left=b.x+this.e.dx+"px";this.g.style.display="block"}},hide:function(){this.data=null;this.g.style.display="none"},disable:function(){this.Ea=true},enable:function(){this.Ea=false},types:{"default":dhtmlx.Template.fromHTML("{obj.id}")},template_item_start:dhtmlx.Template.empty,template_item_end:dhtmlx.Template.empty};
dhtmlx.AutoTooltip={tooltip_setter:function(a,b){var c=new dhtmlx.ui.Tooltip(b);this.attachEvent("onMouseMove",function(d,e){c.show(this.get(d),dhtmlx.html.pos(e))});this.attachEvent("onMouseOut",function(){c.hide()});this.attachEvent("onMouseMoving",function(){c.hide()});return c}};dhtmlx.compat=function(a,b){dhtmlx.compat[a]&&dhtmlx.compat[a](b)};
(function(){if(!window.dhtmlxError){var a=function(){};window.dhtmlxError={catchError:a,throwError:a};window.convertStringToBoolean=function(c){return!!c};window.dhtmlxEventable=function(c){dhtmlx.extend(c,dhtmlx.EventSystem)};var b={getXMLTopNode:function(){},doXPath:function(c){return dhtmlx.DataDriver.xml.xpath(this.xml,c)},xmlDoc:{responseXML:true}};dhtmlx.compat.dataProcessor=function(c){var d="_sendData",e="_in_progress",f="_tMode",g="_waitMode";c[d]=function(h,j){if(h){if(j)this[e][j]=(new Date).valueOf();
if(!this.callEvent("onBeforeDataSending",j?[j,this.getState(j)]:[]))return false;var l=this,i=this.serverProcessor;this[f]!="POST"?dhtmlx.ajax().get(i+(i.indexOf("?")!=-1?"&":"?")+this.serialize(h,j),"",function(o,n){b.xml=dhtmlx.DataDriver.xml.checkResponse(o,n);l.afterUpdate(l,null,null,null,b)}):dhtmlx.ajax().post(i,this.serialize(h,j),function(o,n){b.xml=dhtmlx.DataDriver.xml.checkResponse(o,n);l.afterUpdate(l,null,null,null,b)});this[g]++}}}}})();
dhtmlx.DataProcessor={lb:function(a){var b="_methods";a[b]=["setItemStyle","","changeId","remove"];this.attachEvent("onAfterAdd",function(c){a.setUpdated(c,true,"inserted")});this.data.attachEvent("onStoreLoad",dhtmlx.bind(function(c,d){c.getUserData&&c.getUserData(d,this.xa)},this));this.attachEvent("onBeforeDelete",function(c){var d=a.getState(c);if(d=="inserted"){a.setUpdated(c,false);return true}if(d=="deleted")return false;if(d=="true_deleted")return true;a.setUpdated(c,true,"deleted");return false});
this.attachEvent("onAfterEditStop",function(c){a.setUpdated(c,true,"updated")});b="_getRowData";a[b]=function(c){c=this.obj.data.get(c);var d={};for(var e in c)if(e.indexOf("_")!==0)d[e]=c[e];return d};b="_clearUpdateFlag";a[b]=function(){};this.xa={};a.attachEvent("insertCallback",this.Fa);a.attachEvent("updateCallback",this.Fa);a.attachEvent("deleteCallback",function(c,d){this.obj.setUserData(d,this.action_param,"true_deleted");this.obj.remove(d)});dhtmlx.compat("dataProcessor",a)},Fa:function(a,
b){this.obj.data.set(b,dhtmlx.DataDriver.xml.getDetails(a.firstChild));this.obj.data.refresh(b)},setItemStyle:function(a,b){if(a=this.s(a))a.style.cssText+=";"+b},changeId:function(a,b){this.data.order[this.data.indexById(a)]=b;this.data.pull[b]=this.data.pull[a];this.data.get(b).id=b;delete this.data.pull[a];this.data.refresh()},setUserData:function(a,b,c){if(a)this.data.get(a)[b]=c;else this.xa[b]=c},getUserData:function(a,b){return a?this.data.get(a)[b]:this.xa[b]}};
(function(){var a="_dp_init";dhtmlx.DataProcessor[a]=dhtmlx.DataProcessor.lb})();
dhtmlx.compat.dnd=function(){if(window.dhtmlDragAndDropObject){var a="_dragged",b=dhtmlDragAndDropObject.prototype.checkLanding;dhtmlDragAndDropObject.prototype.checkLanding=function(j,l,i){b.apply(this,arguments);if(!i){var o=dhtmlx.DragControl.v=dhtmlx.DragControl.v||{};o.from=this.dragStartObject;dhtmlx.DragControl.U(j,l,true)}};var c=dhtmlDragAndDropObject.prototype.stopDrag;dhtmlDragAndDropObject.prototype.stopDrag=function(j,l,i){if(!i)if(dhtmlx.DragControl.o){dhtmlx.DragControl.u=d.dragStartNode;
dhtmlx.DragControl.ba(j,true)}c.apply(this,arguments)};var d=new dhtmlDragAndDropObject,e=dhtmlx.DragControl.ua;dhtmlx.DragControl.ua=function(){e.apply(this,arguments);var j=dhtmlx.DragControl.v;if(j){for(var l=[],i=[],o=0;o<j.source.length;o++){l[o]={idd:j.source[o]};i.push(j.source[o])}d.dragStartNode={parentNode:{},parentObject:{idd:l,id:i.length==1?i[0]:i,treeNod:{object:j.from}}};d.dragStartNode.parentObject.treeNod[a]=l;d.dragStartObject=j.from}};var f=dhtmlx.DragControl.U;dhtmlx.DragControl.U=
function(j,l,i){f.apply(this,arguments);if(!this.o&&!i)j=d.checkLanding(j,l,true)};var g=dhtmlx.DragControl.ba;dhtmlx.DragControl.ba=function(j,l){g.apply(this,arguments);d.lastLanding&&!l&&d.stopDrag(j,false,true)};var h=dhtmlx.DragControl.getMaster;dhtmlx.DragControl.getMaster=function(j){var l=null;if(j)l=h.apply(this,arguments);if(!l){l=d.dragStartObject;for(var i=[],o=l[a],n=0;n<o.length;n++)i.push(o[n].idd||o[n].id);dhtmlx.DragControl.v.source=i}return l}}};
dhtmlx.DataMove={j:function(){},copy:function(a,b,c,d){var e=this.get(a);if(e){if(c)e=c.externalData(e);c=c||this;return c.add(c.externalData(e,d),b)}},move:function(a,b,c,d){if(a instanceof Array)for(d=0;d<a.length;d++){var e=(c||this).indexById(this.move(a[d],b,c,dhtmlx.uid()));if(a[d+1])b=e+(this.indexById(a[d+1])<e?0:1)}else{nid=a;if(!(b<0)){var f=this.get(a);if(f){if(!c||c==this)this.data.move(this.indexById(a),b);else{nid=c.add(c.externalData(f,d),b);this.remove(a)}return nid}}}},moveUp:function(a,
b){return this.move(a,this.indexById(a)-(b||1))},moveDown:function(a,b){return this.moveUp(a,(b||1)*-1)},moveTop:function(a){return this.move(a,0)},moveBottom:function(a){return this.move(a,this.data.dataCount()-1)},externalData:function(a,b){var c=dhtmlx.extend({},a);c.id=b||dhtmlx.uid();c.$selected=c.$template=null;return c}};
dhtmlx.DragControl={w:dhtmlx.toArray(["dummy"]),addDrop:function(a,b,c){a=dhtmlx.toNode(a);a.dhx_drop=this.La(b);if(c)a.dhx_master=true},La:function(a){a=a||dhtmlx.DragControl;var b=this.w.find(a);if(b<0){b=this.w.length;this.w.push(a)}return b},addDrag:function(a,b){a=dhtmlx.toNode(a);a.dhx_drag=this.La(b);dhtmlx.event(a,"mousedown",this.Pb,a)},Pb:function(a){if(dhtmlx.DragControl.u){dhtmlx.DragControl.ra();dhtmlx.DragControl.destroyDrag()}dhtmlx.DragControl.u=this;dhtmlx.DragControl.N=dhtmlx.event(document.body,
"mousemove",dhtmlx.DragControl.ua);dhtmlx.DragControl.O=dhtmlx.event(document.body,"mouseup",dhtmlx.DragControl.ra);a.cancelBubble=true;return false},ra:function(){dhtmlx.DragControl.N=dhtmlx.eventRemove(dhtmlx.DragControl.N);dhtmlx.DragControl.O=dhtmlx.eventRemove(dhtmlx.DragControl.O)},ua:function(a){dhtmlx.DragControl.ra();if(dhtmlx.DragControl.createDrag(a)){dhtmlx.DragControl.sendSignal("start");dhtmlx.DragControl.N=dhtmlx.event(document.body,"mousemove",dhtmlx.DragControl.Ua);dhtmlx.DragControl.O=
dhtmlx.event(document.body,"mouseup",dhtmlx.DragControl.ba);dhtmlx.DragControl.Ua(a)}},ba:function(a){dhtmlx.DragControl.N=dhtmlx.eventRemove(dhtmlx.DragControl.N);dhtmlx.DragControl.O=dhtmlx.eventRemove(dhtmlx.DragControl.O);if(dhtmlx.DragControl.o){dhtmlx.DragControl.onDrop(dhtmlx.DragControl.u,dhtmlx.DragControl.o,this.I,a);dhtmlx.DragControl.onDragOut(dhtmlx.DragControl.u,dhtmlx.DragControl.o,null,a)}dhtmlx.DragControl.destroyDrag();dhtmlx.DragControl.sendSignal("stop")},Ua:function(a){var b=
dhtmlx.html.pos(a);dhtmlx.DragControl.q.style.top=b.y+dhtmlx.DragControl.top+"px";dhtmlx.DragControl.q.style.left=b.x+dhtmlx.DragControl.left+"px";if(dhtmlx.DragControl.bb)dhtmlx.DragControl.bb=false;else dhtmlx.DragControl.U(a.srcElement||a.target,a);a.cancelBubble=true;return false},U:function(a,b){for(;a&&a.tagName!="BODY";){if(a.dhx_drop){if(this.o&&(this.o!=a||a.dhx_master))this.onDragOut(this.u,this.o,a,b);if(!this.o||this.o!=a||a.dhx_master){this.o=null;if(this.I=this.onDragIn(dhtmlx.DragControl.u,
a,b))this.o=a;return}return}a=a.parentNode}if(this.o)this.o=this.I=this.onDragOut(this.u,this.o,null,b)},sendSignal:function(a){dhtmlx.DragControl.active=a=="start"},getMaster:function(a){return this.w[a.dhx_drag||a.dhx_drop]},getContext:function(){return this.v},createDrag:function(a){var b=dhtmlx.DragControl.u,c=this.w[b.dhx_drag],d;if(c.onDragCreate){d=c.onDragCreate(b,a);d.style.position="absolute";d.style.zIndex=dhtmlx.zIndex.drag;d.onmousemove=dhtmlx.DragControl.cb}else{var e=dhtmlx.DragControl.onDrag(b,
a);if(!e)return false;d=document.createElement("DIV");d.innerHTML=e;d.className="dhx_drag_zone";d.onmousemove=dhtmlx.DragControl.cb;document.body.appendChild(d)}dhtmlx.DragControl.q=d;return true},cb:function(){dhtmlx.DragControl.bb=true},destroyDrag:function(){var a=dhtmlx.DragControl.u,b=this.w[a.dhx_drag];b&&b.onDragDestroy?b.onDragDestroy(a,dhtmlx.DragControl.q):dhtmlx.html.remove(dhtmlx.DragControl.q);dhtmlx.DragControl.I=dhtmlx.DragControl.u=dhtmlx.DragControl.o=dhtmlx.DragControl.q=null},top:5,
left:5,onDragIn:function(a,b,c){var d=this.w[b.dhx_drop];if(d.onDragIn&&d!=this)return d.onDragIn(a,b,c);b.className+=" dhx_drop_zone";return b},onDragOut:function(a,b,c,d){var e=this.w[b.dhx_drop];if(e.onDragOut&&e!=this)return e.onDragOut(a,b,c,d);b.className=b.className.replace("dhx_drop_zone","");return null},onDrop:function(a,b,c,d){var e=this.w[b.dhx_drop];dhtmlx.DragControl.v.from=dhtmlx.DragControl.getMaster(a);if(e.onDrop&&e!=this)return e.onDrop(a,b,c,d);b.appendChild(a)},onDrag:function(a,
b){var c=this.w[a.dhx_drag];if(c.onDrag&&c!=this)return c.onDrag(a,b);dhtmlx.DragControl.v={source:a,from:a};return"<div style='"+a.style.cssText+"'>"+a.innerHTML+"</div>"}};
dhtmlx.DragItem={j:function(){if(!this.e||this.e.drag)dhtmlx.DragItem.Oa(this);else if(this.e)this.drag_setter=function(a,b){if(b){this.Oa(this);delete this.drag_setter}return b};if(this.dragMarker){this.attachEvent("onBeforeDragIn",this.dragMarker);this.attachEvent("onDragOut",this.dragMarker)}},Oa:function(a){dhtmlx.DragControl.addDrop(a.g,a,true);dhtmlx.DragControl.addDrag(a.g,a)},onDragIn:function(a,b,c){b=this.locate(c)||null;var d=dhtmlx.DragControl.v,e=dhtmlx.DragControl.getMaster(a);a=this.s(b)||
this.g;if(a==dhtmlx.DragControl.I)return a;d.target=b;d.to=e;if(!this.callEvent("onBeforeDragIn",[d,c]))return d.id=null;dhtmlx.html.addCss(a,"dhx_drag_over");return a},onDragOut:function(a,b,c,d){a=this.locate(d)||null;c=this.s(a)||(c?dhtmlx.DragControl.getMaster(c).g:window.undefined);if(c==dhtmlx.DragControl.I)return null;c=dhtmlx.DragControl.v;dhtmlx.html.removeCss(dhtmlx.DragControl.I,"dhx_drag_over");c.target=c.to=null;this.callEvent("onDragOut",[c,d]);return null},onDrop:function(a,b,c,d){a=
dhtmlx.DragControl.v;a.to=this;a.index=a.target?this.indexById(a.target):this.dataCount();a.new_id=dhtmlx.uid();if(this.callEvent("onBeforeDrop",[a,d])){if(a.from==a.to)this.move(a.source,a.index);else a.from&&a.from.move(a.source,a.index,a.to,a.new_id);this.callEvent("onAfterDrop",[a,d])}},onDrag:function(a,b){a=this.locate(b);var c=[a];if(a){if(this.getSelected){var d=this.getSelected();if(dhtmlx.PowerArray.find.call(d,a)!=-1)c=d}var e=dhtmlx.DragControl.v={source:c,start:a};e.from=this;if(this.callEvent("onBeforeDrag",
[e,b]))return e.html||this.M(this.get(a))}return null}};
dhtmlx.EditAbility={j:function(){this.V=this.z=null;this.attachEvent("onEditKeyPress",function(a,b,c){if(a==13&&!c)this.stopEdit();else a==27&&this.stopEdit(true)});this.attachEvent("onBeforeRender",function(){this.stopEdit()})},isEdit:function(){return this.z},edit:function(a){if(this.stopEdit(false,a))if(this.callEvent("onBeforeEditStart",[a])){var b=this.data.get(a);if(!b.$template){b.$template="edit";this.data.refresh(a);this.z=a;this.Ub(a);this.V(true,b);this.callEvent("onAfterEditStart",[a])}}},
stopEdit:function(a,b){if(!this.z)return true;if(this.z==b)return false;if(!this.callEvent("onBeforeEditStop",[this.z]))return false;var c=this.data.get(this.z);c.$template=null;a||this.V(false,c);a=this.z;this.V=this.z=null;this.data.refresh(a);this.callEvent("onAfterEditStop",[a]);return true},Ub:function(a){var b=this.s(a),c="",d="",e=[];if(b){var f=b.getElementsByTagName("*"),g="";for(a=0;a<f.length;a++)if(f[a].nodeType==1&&(g=f[a].getAttribute("bind"))){c+="els["+e.length+"].value="+g+";";d+=
g+"=els["+e.length+"].value;";e.push(f[a]);f[a].className+=" dhx_allow_selection";f[a].onselectstart=this.ib}f=null}c=Function("obj","els",c);d=Function("obj","els",d);this.V=function(h,j){if(h){c(j,e);e.length&&e[0].select&&e[0].select()}else d(j,e)}},ib:function(a){return(a||event).cancelBubble=true}};
dhtmlx.KeyEvents={j:function(){dhtmlx.event(this.g,"keypress",this.Lb,this)},Lb:function(a){a=a||event;var b=a.which||a.keyCode;this.callEvent(this.z?"onEditKeyPress":"onKeyPress",[b,a.ctrlKey,a.shiftKey,a])}};
dhtmlx.MouseEvents={j:function(){if(this.on_click){dhtmlx.event(this.g,"click",this.Ib,this);dhtmlx.event(this.g,"contextmenu",this.Jb,this)}this.on_dblclick&&dhtmlx.event(this.g,"dblclick",this.Kb,this);if(this.on_mouse_move){dhtmlx.event(this.g,"mousemove",this.Xa,this);dhtmlx.event(this.g,dhtmlx.H?"mouseleave":"mouseout",this.Xa,this)}},Ib:function(a){return this.pa(a,this.on_click,"ItemClick")},Kb:function(a){return this.pa(a,this.on_dblclick,"ItemDblClick")},Jb:function(a){var b=dhtmlx.html.locate(a,
this.r);if(b&&!this.callEvent("onBeforeContextMenu",[b,a]))return dhtmlx.html.preventEvent(a)},Xa:function(a){if(dhtmlx.H)a=document.createEventObject(event);this.Ta&&window.clearTimeout(this.Ta);this.callEvent("onMouseMoving",[a]);this.Ta=window.setTimeout(dhtmlx.bind(function(){a.type=="mousemove"?this.Mb(a):this.Nb(a)},this),500)},Mb:function(a){this.pa(a,this.on_mouse_move,"MouseMove")||this.callEvent("onMouseOut",[a||event])},Nb:function(a){this.callEvent("onMouseOut",[a||event])},pa:function(a,
b,c){a=a||event;for(var d=a.target||a.srcElement,e="",f=null,g=false;d&&d.parentNode;){if(!g&&d.getAttribute)if(f=d.getAttribute(this.r)){d.getAttribute("userdata")&&this.callEvent("onLocateData",[f,d]);if(!this.callEvent("on"+c,[f,a,d]))return;g=true}if(e=d.className){e=e.split(" ");e=e[0]||e[1];if(b[e])return b[e].call(this,a,f,d)}d=d.parentNode}return g}};
dhtmlx.SelectionModel={j:function(){this.l=dhtmlx.toArray();this.data.attachEvent("onStoreUpdated",dhtmlx.bind(this.jb,this))},jb:function(a,b,c){if(c=="delete")this.l.remove(a);else if(!this.data.dataCount())this.l=dhtmlx.toArray()},Y:function(a,b,c){if(!c&&!this.callEvent("onBeforeSelect",[a,b]))return false;this.data.get(a).$selected=b;c?c.push(a):this.sa(a);return true},select:function(a,b,c){if(!a)return this.selectAll();if(a instanceof Array)for(var d=0;d<a.length;d++)this.select(a[d],b,c);
else{if(c&&this.l.length)return this.selectAll(this.l[this.l.length-1],a);if(!b&&(this.l.length!=1||this.l[0]!=a))this.unselectAll();if(this.isSelected(a))b&&this.unselect(a);else if(this.Y(a,true)){this.l.push(a);this.callEvent("onAfterSelect",[a])}}},unselect:function(a){if(!a)return this.unselectAll();this.isSelected(a)&&this.Y(a,false)&&this.l.remove(a)},selectAll:function(a,b){var c,d=[];c=a||b?this.data.getRange(a,b):this.data.getRange();c.each(function(e){var f=this.data.get(e.id);if(!f.$selected){this.l.push(e.id);
this.Y(e.id,true,d)}return e.id},this);this.sa(d)},unselectAll:function(){var a=[];this.l.each(function(b){this.Y(b,false,a)},this);this.l=dhtmlx.toArray();this.sa(a)},isSelected:function(a){return this.l.find(a)!=-1},getSelected:function(a){switch(this.l.length){case 0:return a?[]:"";case 1:return a?[this.l[0]]:this.l[0];default:return[].concat(this.l)}},Fb:function(a){return a.length>100||a.length>this.data.dataCount/2},sa:function(a){if(typeof a!="object")a=[a];if(a.length){if(this.Fb(a))this.data.refresh();
else for(var b=0;b<a.length;b++)this.render(a[b],this.data.get(a[b]),"update");this.callEvent("onSelectChange",[a])}}};
dhtmlx.RenderStack={j:function(){this.q=document.createElement("DIV")},M:function(a){this.callEvent("onItemRender",[a]);return this.type.Ra(a,this.type)+(a.$template?this.type["template_"+a.$template]:this.type.template)(a,this.type)+this.type.Qa},wa:function(a){this.q.innerHTML=this.M(a);return this.q.firstChild},s:function(a){if(this.k)return this.k[a];this.k={};for(var b=this.h.childNodes,c=0;c<b.length;c++){var d=b[c].getAttribute(this.r);if(d)this.k[d]=b[c]}return this.s(a)},locate:function(a){return dhtmlx.html.locate(a,
this.r)},show:function(a){if(a=this.s(a))this.h.scrollTop=a.offsetTop-this.h.offsetTop},render:function(a,b,c){if(a){var d=this.s(a);switch(c){case "update":if(!d)return;b=this.k[a]=this.wa(b);dhtmlx.html.insertBefore(b,d);dhtmlx.html.remove(d);break;case "delete":if(!d)return;dhtmlx.html.remove(d);delete this.k[a];break;case "add":b=this.k[a]=this.wa(b);dhtmlx.html.insertBefore(b,this.s(this.data.next(a)),this.h);break;case "move":this.render(a,b,"delete");this.render(a,b,"add");break;default:break}}else if(this.callEvent("onBeforeRender",
[this.data])){this.h.innerHTML=this.data.getRange().map(this.M,this).join("");this.k=null;this.callEvent("onAfterRender",[])}},pager_setter:function(a,b){this.attachEvent("onBeforeRender",function(){var e=this.e.pager.e;if(e.page==-1)return false;this.data.min=e.page*e.size;this.data.max=(e.page+1)*e.size-1;return true});var c=new dhtmlx.ui.pager(b),d=dhtmlx.bind(function(){this.data.refresh()},this);c.attachEvent("onRefresh",d);this.data.attachEvent("onStoreUpdated",function(){var e=this.dataCount();
if(e!=c.e.count){c.e.count=e;if(c.e.page==-1)c.e.page=0;c.refresh()}});return c},height_setter:function(a,b){if(b=="auto"){this.attachEvent("onAfterRender",this.Aa);dhtmlx.event(window,"resize",dhtmlx.bind(this.Aa,this))}return b},Aa:function(){this.h.style.overflow="hidden";this.h.style.height="1px";var a=this.h.scrollHeight;this.h.style.height=a+"px";if(dhtmlx.Pa){var b=this.h.scrollHeight;if(b!=a)this.h.style.height=b+"px"}this.g.style.height=this.h.style.height},ka:function(){var a=this.type,
b=(a.border||0)+(a.padding||0)*2+(a.margin||0)*2;return{x:a.width+b,y:a.height+b}},x_count_setter:function(a,b){var c=this.ka();this.h.style.width=c.x*b+(this.e.height!="auto"?18:0)+"px";return b},y_count_setter:function(a,b){a=this.ka();this.h.style.height=a.y*b+"px";return b}};
dhtmlx.VirtualRenderStack={j:function(){this.k={};this.h.style.overflowY="scroll";dhtmlx.event(this.h,"scroll",dhtmlx.bind(this.$a,this));dhtmlx.event(window,"resize",dhtmlx.bind(function(){this.render()},this));this.R=[];this.attachEvent("onItemRender",function(a){a.$template=="loading"&&this.R.push(this.data.id(a))})},s:function(a){return this.k[a]},show:function(a){range=this.Ma();var b=this.data.indexById(a),c=Math.floor(b/range.ja)*range.ca;this.h.scrollTop=c},render:function(a,b,c){if(a){var d=
this.s(a);switch(c){case "update":if(!d)return;a=this.k[a]=this.wa(b);dhtmlx.html.insertBefore(a,d);dhtmlx.html.remove(d);break;default:this.Sb();break}}else if(this.callEvent("onBeforeRender",[this.data])){this.k={};this.$a(null,true);this.fb=false;this.callEvent("onAfterRender",[])}},Sb:function(){if(!this.fb){this.fb=true;window.setTimeout(dhtmlx.bind(function(){this.render()},this),1)}},fa:function(a){var b=document.createElement("DIV");b.style.cssText="height:"+a+"px; width:100%; overflow:hidden;";
return b},$a:function(a,b){this.R=[];var c=this.Ma();if(!this.h.firstChild||b){this.h.innerHTML="";this.h.appendChild(this.fa(c.Hb));this.C=[this.h.firstChild]}for(a=c.B;a<=c.oa;){for(;this.C[a]&&this.C[a].wb&&a<=c.oa;)a++;if(a>c.oa)break;for(var d=a;!this.C[d];)d--;var e=this.C[d],f=a*c.ja+(this.data.min||0);if(f>(this.data.max||Infinity))break;var g=Math.min(f+c.ja-1,this.data.max||Infinity),h=this.fa(c.ca),j=this.data.getIndexRange(f,g);if(!j.length)break;h.innerHTML=j.map(this.M,this).join("");
for(var l=0;l<j.length;l++)this.k[this.data.idByIndex(f+l)]=h.childNodes[l];var i=parseInt(e.style.height,10),o=(a-d)*c.ca,n=i-o-c.ca;dhtmlx.html.insertBefore(h,o?e.nextSibling:e,this.h);this.C[a]=h;h.wb=true;if(o<=0&&n>0){e.style.height=n+"px";this.C[a+1]=e}else{if(o<0)dhtmlx.html.remove(e);else e.style.height=o+"px";if(n>0){var q=this.C[a+1]=this.fa(n);dhtmlx.html.insertBefore(q,h.nextSibling,this.h)}}a++}if(this.R.length){a=this.indexById(this.R[0]);h=this.indexById(this.R.pop())+1;if(h>a){if(!this.callEvent("onDataRequest",
[a,h-a]))return false;this.data.feed.call(this,a,h-a)}}},Ma:function(){var a=this.h.scrollTop,b=Math.max(this.h.scrollWidth,this.h.offsetWidth)-18,c=this.h.offsetHeight,d=this.ka(),e=Math.floor(b/d.x)||1,f=Math.floor(a/d.y);c=Math.ceil((c+a)/d.y)-1;var g=this.data.max?this.data.max-this.data.min:this.data.dataCount(),h=Math.ceil(g/e)*d.y;return{B:f,oa:c,ac:a,Hb:h,ca:d.y,ja:e}}};
dhtmlx.DataStore=function(){this.name="DataStore";dhtmlx.extend(this,dhtmlx.EventSystem);this.setDriver("xml");this.pull={};this.order=dhtmlx.toArray();this.$b=false};
dhtmlx.DataStore.prototype={setDriver:function(a){this.driver=dhtmlx.DataDriver[a]},eb:function(a){if(a.item){if(!(a.item instanceof Array))a.item=[a.item];for(var b=0;b<a.item.length;b++){var c=a.item[b],d=this.id(c);a.item[b]=d;this.pull[d]=c;c.parent=a.id;c.level=a.level+1;this.eb(c)}}},Ob:function(a){for(var b=this.driver.getInfo(a),c=this.driver.getRecords(a),d=(b.B||0)*1,e=0,f=0;f<c.length;f++){var g=this.driver.getDetails(c[f]),h=this.id(g);if(!this.pull[h]){this.order[e+d]=h;e++}this.pull[h]=
g;if(this.$b){g.level=1;this.eb(g)}}for(f=0;f<b.L;f++)if(!this.order[f]){h=dhtmlx.uid();g={id:h,$template:"loading"};this.pull[h]=g;this.order[f]=h}this.callEvent("onStoreLoad",[this.driver,a]);this.refresh()},id:function(a){return a.id||(a.id=dhtmlx.uid())},get:function(a){return this.pull[a]},set:function(a,b){this.pull[a]=b;this.refresh()},refresh:function(a){a?this.callEvent("onStoreUpdated",[a,this.pull[a],"update"]):this.callEvent("onStoreUpdated",[null,null,null])},getRange:function(a,b){if(arguments.length){a=
this.indexById(a);b=this.indexById(b);if(a>b){var c=b;b=a;a=c}}else{a=this.min||0;b=Math.min(this.max||Infinity,this.dataCount()-1)}return this.getIndexRange(a,b)},getIndexRange:function(a,b){b=Math.min(b,this.dataCount()-1);var c=dhtmlx.toArray();for(a=a;a<=b;a++)c.push(this.get(this.order[a]));return c},dataCount:function(){return this.order.length},exists:function(a){return!!this.pull[a]},move:function(a,b){if(!(a<0||b<0)){var c=this.idByIndex(a),d=this.get(c);this.order.removeAt(a);this.order.insertAt(c,
Math.min(this.order.length,b));this.callEvent("onStoreUpdated",[c,d,"move"])}},add:function(a,b){var c=this.id(a),d=this.dataCount();if(dhtmlx.isNotDefined(b)||b<0)b=d;if(b>d)b=Math.min(this.order.length,b);if(this.callEvent("onbeforeAdd",[c,b])){if(this.exists(c))return null;this.pull[c]=a;this.order.insertAt(c,b);if(this.A){var e=this.A.length;if(!b&&this.order.length)e=0;this.A.insertAt(c,e)}this.callEvent("onafterAdd",[c,b]);this.callEvent("onStoreUpdated",[c,a,"add"]);return c}},remove:function(a){if(a instanceof
Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else if(this.callEvent("onbeforedelete",[a])){if(!this.exists(a))return null;b=this.get(a);this.order.remove(a);this.A&&this.A.remove(a);delete this.pull[a];this.callEvent("onafterdelete",[a]);this.callEvent("onStoreUpdated",[a,b,"delete"])}},clearAll:function(){this.pull={};this.order=dhtmlx.toArray();this.A=null;this.callEvent("onClearAll",[]);this.refresh()},idByIndex:function(a){return this.order[a]},indexById:function(a){return a=this.order.find(a)},
next:function(a,b){return this.order[this.indexById(a)+(b||1)]},first:function(){return this.order[0]},last:function(){return this.order[this.order.length-1]},previous:function(a,b){return this.order[this.indexById(a)-(b||1)]},sort:function(a,b,c){var d=a;if(typeof a=="function")d={as:a,dir:b};else if(typeof a=="string")d={by:a,dir:b,as:c};var e=[d.by,d.dir,d.as];if(this.callEvent("onbeforesort",e)){if(this.order.length){var f=dhtmlx.sort.create(d),g=this.getRange(this.first(),this.last());g.sort(f);
this.order=g.map(function(h){return this.id(h)},this)}this.refresh();this.callEvent("onaftersort",e)}},filter:function(a,b){if(this.A){this.order=this.A;delete this.A}if(a){var c=a;if(typeof a=="string"){a=dhtmlx.Template.setter(0,a);c=function(e,f){return a(e).toLowerCase().indexOf(f)!=-1}}b=(b||"").toString().toLowerCase();var d=dhtmlx.toArray();this.order.each(function(e){c(this.get(e),b)&&d.push(e)},this);this.A=this.order;this.order=d}this.refresh()},each:function(a,b){for(var c=0;c<this.order.length;c++)a.call(b||
this,this.get(this.order[c]))},provideApi:function(a,b){b&&this.mapEvent({onbeforesort:a,onaftersort:a,onbeforeadd:a,onafteradd:a,onbeforedelete:a,onafterdelete:a});for(var c=["sort","add","remove","exists","idByIndex","indexById","get","set","refresh","dataCount","filter","next","previous","clearAll","first","last"],d=0;d<c.length;d++)a[c[d]]=dhtmlx.methodPush(this,c[d])}};
dhtmlx.sort={create:function(a){return dhtmlx.sort.dir(a.dir,dhtmlx.sort.by(a.by,a.as))},as:{"int":function(a,b){a*=1;b*=1;return a>b?1:a<b?-1:0},string_strict:function(a,b){a=a.toString();b=b.toString();return a>b?1:a<b?-1:0},string:function(a,b){a=a.toString().toLowerCase();b=b.toString().toLowerCase();return a>b?1:a<b?-1:0}},by:function(a,b){if(typeof b!="function")b=dhtmlx.sort.as[b||"string"];a=dhtmlx.Template.setter(0,a);return function(c,d){return b(a(c),a(d))}},dir:function(a,b){if(a=="asc")return b;
return function(c,d){return b(c,d)*-1}}};dhtmlx.ajax=function(a,b,c){if(arguments.length!==0){var d=new dhtmlx.ajax;if(c)d.master=c;d.get(a,null,b)}if(!this.getXHR)return new dhtmlx.ajax;return this};
dhtmlx.ajax.prototype={getXHR:function(){return dhtmlx.H?new ActiveXObject("Microsoft.xmlHTTP"):new XMLHttpRequest},send:function(a,b,c){var d=this.getXHR();if(typeof c=="function")c=[c];if(typeof b=="object"){var e=[];for(var f in b)e.push(f+"="+encodeURIComponent(b[f]));b=e.join("&")}if(b&&!this.post){a=a+(a.indexOf("?")!=-1?"&":"?")+b;b=null}d.open(this.post?"POST":"GET",a,!this.db);this.post&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded");if(!this.db){var g=this;d.onreadystatechange=
function(){if(!d.readyState||d.readyState==4){if(c&&g)for(var h=0;h<c.length;h++)if(c[h])c[h].call(g.master||g,d.responseText,d.responseXML,d);c=d=g=g.master=null}}}d.send(b||null);return d},get:function(a,b,c){this.post=false;return this.send(a,b,c)},post:function(a,b,c){this.post=true;return this.send(a,b,c)},sync:function(){this.db=true;return this}};
dhtmlx.DataLoader={j:function(){this.data=new dhtmlx.DataStore},load:function(a,b,c){this.callEvent("onXLS",[]);if(typeof b=="string"){this.data.setDriver(b);b=c}if(!this.data.feed)this.data.feed=function(d,e){if(this.W)return this.W=[d,e];else this.W=true;this.load(a+(a.indexOf("?")==-1?"?":"&")+"posStart="+d+"&count="+e,function(){var f=this.W;this.W=false;typeof f=="object"&&this.data.feed.apply(this,f)})};dhtmlx.ajax(a,[this.Wa,b],this)},parse:function(a,b){this.callEvent("onXLS",[]);b&&this.data.setDriver(b);
this.Wa(a,null)},Wa:function(a,b){this.data.Ob(this.data.driver.toObject(a,b));this.callEvent("onXLE",[])}};dhtmlx.DataDriver={};dhtmlx.DataDriver.json={toObject:function(a){if(typeof a=="string"){eval("dhtmlx.temp="+a);return dhtmlx.temp}return a},getRecords:function(a){if(a&&!(a instanceof Array))return[a];return a},getDetails:function(a){return a},getInfo:function(a){return{L:a.total_count||0,B:a.pos||0}}};
dhtmlx.DataDriver.html={toObject:function(a){if(typeof a=="string"){var b=null;if(a.indexOf("<")==-1)b=dhtmlx.toNode(a);if(!b){b=document.createElement("DIV");b.innerHTML=a}return b.getElementsByTagName(this.tag)}return a},getRecords:function(a){if(a.tagName)return a.childNodes;return a},getDetails:function(a){return dhtmlx.DataDriver.xml.tagToObject(a)},getInfo:function(){return{L:0,B:0}},tag:"LI"};
dhtmlx.DataDriver.jsarray={toObject:function(a){if(typeof a=="string"){eval("dhtmlx.temp="+a);return dhtmlx.temp}return a},getRecords:function(a){return a},getDetails:function(a){for(var b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{L:0,B:0}}};
dhtmlx.DataDriver.csv={toObject:function(a){return a},getRecords:function(a){return a.split(this.row)},getDetails:function(a){a=this.stringToArray(a);for(var b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{L:0,B:0}},stringToArray:function(a){a=a.split(this.cell);for(var b=0;b<a.length;b++)a[b]=a[b].replace(/^[ \t\n\r]*(\"|)/g,"").replace(/(\"|)[ \t\n\r]*$/g,"");return a},row:"\n",cell:","};
dhtmlx.DataDriver.xml={toObject:function(a,b){if(b&&(b=this.checkResponse(a,b)))return b;if(typeof a=="string")return this.fromString(a);return a},getRecords:function(a){return this.xpath(a,this.records)},records:"/*/item",userdata:"/*/userdata",getDetails:function(a){return this.tagToObject(a,{})},getUserData:function(a,b){b=b||{};var c=this.xpath(a,this.userdata);for(a=0;a<c.length;a++){var d=this.tagToObject(c[a]);b[d.name]=d.value}return b},getInfo:function(a){return{L:a.documentElement.getAttribute("total_count")||
0,B:a.documentElement.getAttribute("pos")||0}},xpath:function(a,b){if(window.XPathResult){var c=a;if(a.nodeName.indexOf("document")==-1)a=a.ownerDocument;var d=[];a=a.evaluate(b,c,null,XPathResult.ANY_TYPE,null);for(b=a.iterateNext();b;){d.push(b);b=a.iterateNext()}return d}return a.selectNodes(b)},tagToObject:function(a,b){b=b||{};for(var c=a.attributes,d=0;d<c.length;d++)b[c[d].name]=c[d].value;var e=false,f=a.childNodes;for(d=0;d<f.length;d++)if(f[d].nodeType==1){var g=f[d].tagName;if(typeof b[g]!=
"undefined"){b[g]instanceof Array||(b[g]=[b[g]]);b[g].push(this.tagToObject(f[d],{}))}else b[f[d].tagName]=this.tagToObject(f[d],{});e=true}if(!c.length&&!e)return this.nodeValue(a);b.value=this.nodeValue(a);return b},nodeValue:function(a){if(a.firstChild)return a.firstChild.data;return""},fromString:function(a){if(window.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");if(window.ActiveXObject){temp=new ActiveXObject("Microsoft.xmlDOM");temp.loadXML(a);return temp}},checkResponse:function(a,
b){if(b&&b.firstChild&&b.firstChild.tagName!="parsererror")return b;if(a=this.from_string(a.responseText.replace(/^[\s]+/,"")))return a}};if(!dhtmlx.attaches)dhtmlx.attaches={};
dhtmlx.attaches.attachAbstract=function(a,b){var c=document.createElement("DIV");c.id="CustomObject_"+dhtmlx.uid();c.style.width="100%";c.style.height="100%";c.cmp="grid";document.body.appendChild(c);this.attachObject(c.id);b.container=c.id;var d=this.vs[this.av];d.grid=new window[a](b);d.gridId=c.id;d.gridObj=c;d.grid.setSizes=function(){this.resize?this.resize():this.render()};var e="_viewRestore";return this.vs[this[e]()].grid};
dhtmlx.attaches.attachDataView=function(a){return this.attachAbstract("dhtmlXDataView",a)};dhtmlx.attaches.attachChart=function(a){return this.attachAbstract("dhtmlXChart",a)};dhtmlx.compat.layout=function(){};
dhtmlXDataView=function(a){this.name="DataView";this.version="3.0";dhtmlx.extend(this,dhtmlx.Settings);this.qa(a,"dhx_dataview");dhtmlx.extend(this,dhtmlx.DataLoader);dhtmlx.extend(this,dhtmlx.EventSystem);dhtmlx.extend(this,dhtmlx.RenderStack);dhtmlx.extend(this,dhtmlx.SelectionModel);dhtmlx.extend(this,dhtmlx.MouseEvents);dhtmlx.extend(this,dhtmlx.KeyEvents);dhtmlx.extend(this,dhtmlx.EditAbility);dhtmlx.extend(this,dhtmlx.DataMove);dhtmlx.extend(this,dhtmlx.DragItem);dhtmlx.extend(this,dhtmlx.DataProcessor);
dhtmlx.extend(this,dhtmlx.AutoTooltip);dhtmlx.extend(this,dhtmlx.Destruction);this.data.attachEvent("onStoreUpdated",dhtmlx.bind(function(){this.render.apply(this,arguments)},this));this.K(a,{drag:false,edit:false,select:"multiselect",type:"default"});this.e.height!="auto"&&dhtmlx.extend(this,dhtmlx.VirtualRenderStack);this.data.provideApi(this,true)};
dhtmlXDataView.prototype={dragMarker:function(a){var b=this.s(a.target);if(this.type.drag_marker){if(this.ga){this.ga.style.backgroundImage="";this.ga.style.backgroundRepeat=""}if(b){b.style.backgroundImage="url("+(dhtmlx.image_path||"")+this.type.drag_marker+")";b.style.backgroundRepeat="no-repeat";this.ga=b}}if(b&&this.e.auto_scroll){a=b.offsetTop;var c=b.offsetHeight,d=this.g.scrollTop,e=this.g.offsetHeight;if(a-c>0&&a-c*0.75<d)d=Math.max(a-c,0);else if(a+c/0.75>d+e)d+=c;this.g.scrollTop=d}return true},
r:"dhx_f_id",on_click:{dhx_dataview_item:function(a,b){if(this.stopEdit(false,b))if(this.e.select)this.e.select=="multiselect"?this.select(b,a.ctrlKey,a.shiftKey):this.select(b)}},on_dblclick:{dhx_dataview_item:function(a,b){this.e.edit&&this.edit(b)}},on_mouse_move:{},types:{"default":{css:"default",template:dhtmlx.Template.fromHTML("<div style='padding:10px; white-space:nowrap; overflow:hidden;'>{obj.text}</div>"),template_edit:dhtmlx.Template.fromHTML("<div style='padding:10px; white-space:nowrap; overflow:hidden;'><textarea style='width:100%; height:100%;' bind='obj.text'></textarea></div>"),
template_loading:dhtmlx.Template.fromHTML("<div style='padding:10px; white-space:nowrap; overflow:hidden;'>Loading...</div>"),width:210,height:115,margin:0,padding:10,border:1}},template_item_start:dhtmlx.Template.fromHTML("<div dhx_f_id='{-obj.id}' class='dhx_dataview_item dhx_dataview_{obj.css}_item{-obj.$selected?_selected:}' style='width:{obj.width}px; height:{obj.height}px; padding:{obj.padding}px; margin:{obj.margin}px; float:left; overflow:hidden;'>"),template_item_end:dhtmlx.Template.fromHTML("</div>")};
dhtmlx.compat("layout");dhtmlx.math={};dhtmlx.math.Zb=["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];dhtmlx.math.toHex=function(a,b){a=parseInt(a,10);for(str="";a>0;){str=this.Zb[a%16]+str;a=Math.floor(a/16)}for(;str.length<b;)str="0"+str;return str};dhtmlx.ui.Map=function(a){this.name="Map";this.r="map_"+dhtmlx.uid();this.Gb=a;this.J=[]};
dhtmlx.ui.Map.prototype={addRect:function(a,b,c){this.Ca(a,"RECT",b,c)},addPoly:function(a,b){this.Ca(a,"POLY",b)},Ca:function(a,b,c,d){var e="";if(arguments.length==4)e="userdata='"+d+"'";this.J.push("<area "+this.Gb+"='"+a+"' shape='"+b+"' coords='"+c.join()+"' "+e+"></area>")},addSector:function(a,b,c,d,e,f,g){var h=[];h.push(d);h.push(Math.floor(e*g));for(var j=b;j<c;j+=Math.PI/18){h.push(Math.floor(d+f*Math.cos(j)));h.push(Math.floor((e+f*Math.sin(j))*g))}h.push(Math.floor(d+f*Math.cos(c)));
h.push(Math.floor((e+f*Math.sin(c))*g));h.push(d);h.push(Math.floor(e*g));return this.addPoly(a,h)},render:function(a){var b=dhtmlx.html.create("DIV");b.style.cssText="position:absolute; width:100%; height:100%; top:0px; left:0px;";a.appendChild(b);var c=dhtmlx.H?"":"src='data:image/gif;base64,R0lGODlhEgASAIAAAP///////yH5BAUUAAEALAAAAAASABIAAAIPjI+py+0Po5y02ouz3pwXADs='";b.innerHTML="<map id='"+this.r+"' name='"+this.r+"'>"+this.J.join("\n")+"</map><img "+c+" class='dhx_map_img' usemap='#"+this.r+
"'>";a.k=b;this.J=[]}};dhtmlx.chart={};
dhtmlx.chart.area={pvt_render_area:function(a,b,c,d,e,f){var g=this.S(a,b,c,d,e),h=Math.floor(g.cellWidth/2);if(b.length){a.globalAlpha=this.e.alpha.call(this,b[0]);a.fillStyle=this.e.color.call(this,b[0]);var j=this.G(b[0],c,d,g),l=this.e.offset?c.x+g.cellWidth*0.5:c.x;a.beginPath();a.moveTo(l,d.y);a.lineTo(l,j);f.addRect(b[0].id,[l-h,j-h,l+h,j+h]);this.e.yAxis||this.renderTextAt(false,!this.e.offset?false:true,l,j-this.e.labelOffset,this.e.label(b[0]));for(var i=1;i<b.length;i++){var o=l+Math.floor(g.cellWidth*
i)-0.5,n=this.G(b[i],c,d,g);a.lineTo(o,n);f.addRect(b[i].id,[o-h,n-h,o+h,n+h]);this.e.yAxis||this.renderTextAt(false,!this.e.offset&&i==b.length-1?"left":"center",o,n-this.e.labelOffset,this.e.label(b[i]))}a.lineTo(l+Math.floor(g.cellWidth*[b.length-1]),d.y);a.lineTo(l,d.y);a.fill()}}};
dhtmlx.chart.stackedArea={pvt_render_stackedArea:function(a,b,c,d,e,f){var g=this.S(a,b,c,d,e),h=Math.floor(g.cellWidth/2),j=[];if(b.length){a.globalAlpha=this.e.alpha.call(this,b[0]);a.fillStyle=this.e.color.call(this,b[0]);var l=e?b[0].$startY:d.y,i=this.e.offset?c.x+g.cellWidth*0.5:c.x,o=this.G(b[0],c,d,g)-(e?d.y-l:0);j[0]=o;a.beginPath();a.moveTo(i,l);a.lineTo(i,o);f.addRect(b[0].id,[i-h,o-h,i+h,o+h]);this.e.yAxis||this.renderTextAt(false,true,i,o-this.e.labelOffset,this.e.label(b[0]));for(var n=
1;n<b.length;n++){var q=i+Math.floor(g.cellWidth*n)-0.5,z=this.G(b[n],c,d,g)-(e?d.y-b[n].$startY:0);j[n]=z;a.lineTo(q,z);f.addRect(b[n].id,[q-h,z-h,q+h,z+h]);this.e.yAxis||this.renderTextAt(false,true,q,z-this.e.labelOffset,this.e.label(b[n]))}a.lineTo(i+Math.floor(g.cellWidth*[b.length-1]),l);if(e)for(n=b.length-1;n>=0;n--){q=i+Math.floor(g.cellWidth*n)-0.5;var A=b[n].$startY;a.lineTo(q,A)}else a.lineTo(i+Math.floor(g.cellWidth*(length-1))-0.5,l);a.lineTo(i,l);a.fill();for(n=0;n<b.length;n++)b[n].$startY=
j[n]}}};
dhtmlx.chart.spline={pvt_render_spline:function(a,b,c,d,e){var f=this.S(a,b,c,d,e);Math.floor(f.cellWidth/2);var g=[];if(b.length){var h=this.e.offset?c.x+f.cellWidth*0.5:c.x;for(e=0;e<b.length;e++){var j=!e?h:Math.floor(f.cellWidth*e)-0.5+h,l=this.G(b[e],c,d,f);g.push({x:j,y:l})}var i=this.Ab(g);for(e=0;e<g.length-1;e++){var o=g[e].x;c=g[e].y;var n=g[e+1].x,q=g[e+1].y;for(d=o;d<n;d++)this.m(a,d,this.ma(d,o,e,i.a,i.b,i.c,i.d),d+1,this.ma(d+1,o,e,i.a,i.b,i.c,i.d),this.e.line.color(b[e]),this.e.line.width);this.m(a,
n-1,this.ma(d,o,e,i.a,i.b,i.c,i.d),n,q,this.e.line.color(b[e]),this.e.line.width);this.ha(a,o,c,b[e],this.e.label(b[e]))}this.ha(a,n,q,b[e],this.e.label(b[e]))}},Ab:function(a){var b,c,d,e,f,g,h,j,l;b=[];m=[];l=a.length;for(var i=0;i<l-1;i++){b[i]=a[i+1].x-a[i].x;m[i]=(a[i+1].y-a[i].y)/b[i]}c=[];d=[];c[0]=0;c[1]=2*(b[0]+b[1]);d[0]=0;d[1]=6*(m[1]-m[0]);for(i=2;i<l-1;i++){c[i]=2*(b[i-1]+b[i])-b[i-1]*b[i-1]/c[i-1];d[i]=6*(m[i]-m[i-1])-b[i-1]*d[i-1]/c[i-1]}e=[];e[l-1]=e[0]=0;for(i=l-2;i>=1;i--)e[i]=(d[i]-
b[i]*e[i+1])/c[i];f=[];g=[];h=[];j=[];for(i=0;i<l-1;i++){f[i]=a[i].y;g[i]=-b[i]*e[i+1]/6-b[i]*e[i]/3+(a[i+1].y-a[i].y)/b[i];h[i]=e[i]/2;j[i]=(e[i+1]-e[i])/(6*b[i])}return{a:f,b:g,c:h,d:j}},ma:function(a,b,c,d,e,f,g){return d[c]+(a-b)*(e[c]+(a-b)*(f[c]+(a-b)*g[c]))}};
dhtmlx.chart.barH={pvt_render_barH:function(a,b,c,d,e,f){var g,h,j,l,i=d.x-c.x,o=!!this.e.yAxis,n=this.la("h");g=n.max;h=n.min;var q=Math.floor((d.y-c.y)/b.length);e||this.Ga(a,b,c,d,h,g,q);if(o){g=parseFloat(this.e.xAxis.end);h=parseFloat(this.e.xAxis.start)}var z=this.P(h,g);l=z[0];j=z[1];var A=l?i/l:10;if(!o){var t=10;A=l?(i-t)/l:10}var x=parseInt(this.e.width,10);if(x*this.i.length+4>q)x=q/this.i.length-4;var F=Math.floor((q-x*this.i.length)/2),y=typeof this.e.radius!="undefined"?parseInt(this.e.radius,
10):Math.round(x/5),D=false,s=this.e.gradient;if(s&&typeof s!="function"){D=s;s=false}else if(s){s=a.createLinearGradient(c.x,c.y,d.x,c.y);this.e.gradient(s)}o||this.m(a,c.x-0.5,c.y,c.x-0.5,d.y,"#000000",1);for(d=0;d<b.length;d++){var C=parseFloat(this.e.value(b[d]));if(C>g)C=g;C-=h;C*=j;var G=c.x,H=c.y+F+d*q+(x+1)*e;if(C<0||this.e.yAxis&&C===0)this.renderTextAt("middle",true,G+10,H+x/2+F,this.e.label(b[d]));else{o||(C+=t/A);var S=s||this.e.color.call(this,b[d]);if(this.e.border){a.beginPath();a.fillStyle=
S;this.F(a,G,H,x,y,A,C,0);a.lineTo(G,0);a.fill();a.fillStyle="#000000";a.globalAlpha=0.37;a.beginPath();this.F(a,G,H,x,y,A,C,0);a.fill()}a.globalAlpha=this.e.alpha.call(this,b[d]);a.fillStyle=s||this.e.color.call(this,b[d]);a.beginPath();var M=this.F(a,G,H,x,y,A,C,this.e.border?1:0);if(s&&!D)a.lineTo(c.x+i,H+(this.e.border?1:0));a.fill();a.globalAlpha=1;if(D!=false){var P=this.Z(a,c.x,H+x,c.x+A*C+2,H,D,S,"x");a.fillStyle=P.gradient;a.beginPath();M=this.F(a,G,H+P.offset,x-P.offset*2,y,A,C,P.offset);
a.fill();a.globalAlpha=1}this.renderTextAt("middle",false,M[0]+3,parseInt(H+(M[1]-H)/2,10),this.e.label(b[d]));f.addRect(b[d].id,[G,H,M[0],M[1]],e)}}},F:function(a,b,c,d,e,f,g,h){var j=0;if(e>f*g){var l=(e-f*g)/e;j=-Math.asin(l)+Math.PI/2}a.moveTo(b,c+h);var i=b+f*g-e-(e?0:h);e<f*g&&a.lineTo(i,c+h);f=c+e;e&&a.arc(i,f,e-h,-Math.PI/2+j,0,false);var o=c+d-e-(e?0:h),n=i+e-(e?h:0);a.lineTo(n,o);var q=i;e&&a.arc(q,o,e-h,0,Math.PI/2-j,false);var z=c+d-h;a.lineTo(b,z);a.lineTo(b,c+h);return[n,z]},Ga:function(a,
b,c,d,e,f,g){this.pb(a,b,c,d,e,f);this.qb(a,b,c,d,g)},qb:function(a,b,c,d,e){if(this.e.yAxis){var f=c.x-0.5,g=d.y+0.5,h=c.y;this.m(a,f,g,f,h,this.e.yAxis.color,1);for(a=0;a<b.length;a++)this.renderTextAt("middle",0,0,h+e/2+a*e,this.e.yAxis.template(b[a]),"dhx_axis_item_y",c.x-5);this.ab(c,d)}},pb:function(a,b,c,d,e,f){var g,h={},j=this.e.xAxis;if(j){b=d.y+0.5;var l=c.x-0.5,i=d.x-0.5;this.m(a,l,b,i,b,j.color,1);if(j.step)g=parseFloat(j.step);if(typeof j.step=="undefined"||typeof j.start=="undefined"||
typeof j.end=="undefined"){h=this.za(e,f);e=h.start;f=h.end;g=h.step;this.e.xAxis.end=f;this.e.xAxis.start=e;this.e.xAxis.step=g}if(g!==0){for(var o=(i-l)*g/(f-e),n=0,q=e;q<=f;q+=g){if(h.fixNum)q=parseFloat((new Number(q)).toFixed(h.fixNum));var z=Math.floor(l+n*o)+0.5;q!=e&&j.lines&&this.m(a,z,b,z,c.y,this.e.xAxis.color,0.2);this.renderTextAt(false,true,z,b+2,j.template(q.toString()),"dhx_axis_item_x");n++}this.renderTextAt(true,false,l,d.y+this.e.padding.bottom-3,this.e.xAxis.title,"dhx_axis_title_x",
d.x-c.x);j.lines&&this.m(a,l,c.y-0.5,i,c.y-0.5,this.e.xAxis.color,0.2)}}}};
dhtmlx.chart.stackedBarH={pvt_render_stackedBarH:function(a,b,c,d,e,f){var g,h,j,l,i=d.x-c.x,o=!!this.e.yAxis;h=this.na(b);g=h.max;h=h.min;var n=Math.floor((d.y-c.y)/b.length);e||this.Ga(a,b,c,d,h,g,n);if(o){g=parseFloat(this.e.xAxis.end);h=parseFloat(this.e.xAxis.start)}j=this.P(h,g);l=j[0];j=j[1];var q=l?i/l:10;if(!o){var z=10;q=l?(i-z)/l:10}l=parseInt(this.e.width,10);if(l+4>n)l=n-4;var A=Math.floor((n-l)/2),t=0,x=false,F=this.e.gradient;x=false;if(F=this.e.gradient)x=true;o||this.m(a,c.x-0.5,
c.y,c.x-0.5,d.y,"#000000",1);for(d=0;d<b.length;d++){if(!e)b[d].$startX=c.x;var y=parseFloat(this.e.value(b[d]));if(y>g)y=g;y-=h;y*=j;var D=c.x,s=c.y+A+d*n;if(e)D=b[d].$startX;if(y<0||this.e.yAxis&&y===0)this.renderTextAt("middle",true,D+10,s+l/2,this.e.label(b[d]));else{o||(y+=z/q);var C=this.e.color.call(this,b[d]);if(this.e.border){a.beginPath();a.fillStyle=C;this.F(a,D,s,l,t,q,y,0);a.lineTo(D,0);a.fill();a.fillStyle="#000000";a.globalAlpha=0.37;a.beginPath();this.F(a,D,s,l,t,q,y,0);a.fill()}a.globalAlpha=
1;a.globalAlpha=this.e.alpha.call(this,b[d]);a.fillStyle=this.e.color.call(this,b[d]);a.beginPath();var G=this.F(a,D,s,l,t,q,y,this.e.border?1:0);if(F&&!x)a.lineTo(c.x+i,s+(this.e.border?1:0));a.fill();if(x!=false){C=this.Z(a,D,s+l,D,s,x,C,"x");a.fillStyle=C.gradient;a.beginPath();G=this.F(a,D,s,l,t,q,y,0);a.fill();a.globalAlpha=1}this.renderTextAt("middle",true,b[d].$startX+(G[0]-b[d].$startX)/2-1,s+(G[1]-s)/2,this.e.label(b[d]));f.addRect(b[d].id,[b[d].$startX,s,G[0],G[1]],e);b[d].$startX=G[0]}}}};
dhtmlx.chart.stackedBar={pvt_render_stackedBar:function(a,b,c,d,e,f){var g,h,j,l=d.y-c.y;j=!!this.e.yAxis;var i=!!this.e.xAxis;h=this.na(b);g=h.max;h=h.min;var o=Math.floor((d.x-c.x)/b.length);e||this.ia(a,b,c,d,h,g,o);if(j){g=parseFloat(this.e.yAxis.end);h=parseFloat(this.e.yAxis.start)}g=this.P(h,g);j=g[0];g=g[1];j=j?l/j:10;var n=parseInt(this.e.width,10);if(n+4>o)n=o-4;var q=Math.floor((o-n)/2),z=this.e.gradient?this.e.gradient:false;i||this.m(a,c.x,d.y+0.5,d.x,d.y+0.5,"#000000",1);for(i=0;i<b.length;i++){var A=
parseFloat(this.e.value(b[i]));if(A){e||(A-=h);A*=g;var t=c.x+q+i*o,x=d.y;if(e)x=b[i].$startY;if(!(x<c.y+1))if(A<0||this.e.yAxis&&A===0)this.renderTextAt(true,true,t+Math.floor(n/2),x,this.e.label(b[i]));else{var F=this.e.color.call(this,b[i]);if(this.e.border){a.beginPath();a.fillStyle=F;this.aa(a,t-1,x,n+2,j,A,0,c.y);a.lineTo(t,x);a.fill();a.fillStyle="#000000";a.globalAlpha=0.37;a.beginPath();this.aa(a,t-1,x,n+2,j,A,0,c.y);a.fill()}a.globalAlpha=this.e.alpha.call(this,b[i]);a.fillStyle=this.e.color.call(this,
b[i]);a.beginPath();var y=this.aa(a,t,x,n,j,A,this.e.border?1:0,c.y);a.fill();a.globalAlpha=1;if(z){F=this.Z(a,t,x,t+n,y[1],z,F,"y");a.fillStyle=F.gradient;a.beginPath();y=this.aa(a,t+F.offset,x,n-F.offset*2,j,A,this.e.border?1:0,c.y);a.fill();a.globalAlpha=1}this.renderTextAt(false,true,t+Math.floor(n/2),y[1]+(x-y[1])/2-7,this.e.label(b[i]));f.addRect(b[i].id,[t,y[1],y[0],b[i].$startY||x],e);b[i].$startY=this.e.border?y[1]+1:y[1]}}}},aa:function(a,b,c,d,e,f,g,h){a.moveTo(b,c);f=c-e*f+g;if(f<h)f=
h;a.lineTo(b,f);e=b+d;f=f;a.lineTo(e,f);var j=b+d;a.lineTo(j,c);a.lineTo(b,c);return[j,f-2*g]}};
dhtmlx.chart.line={pvt_render_line:function(a,b,c,d,e,f){e=this.S(a,b,c,d,e);var g=Math.floor(e.cellWidth/2);if(b.length)for(var h=this.G(b[0],c,d,e),j=this.e.offset?c.x+e.cellWidth*0.5:c.x,l=j,i=1;i<=b.length;i++){var o=Math.floor(e.cellWidth*i)-0.5+l;if(b.length!=i){var n=this.G(b[i],c,d,e);this.m(a,j,h,o,n,this.e.line.color(b[i-1]),this.e.line.width)}this.ha(a,j,h,b[i-1],!!this.e.offset);f.addRect(b[i-1].id,[j-g,h-g,j+g,h+g]);h=n;j=o}},ha:function(a,b,c,d,e){var f=parseInt(this.e.item.radius,10);
a.lineWidth=parseInt(this.e.item.borderWidth,10);a.fillStyle=this.e.item.color(d);a.strokeStyle=this.e.item.borderColor(d);a.beginPath();a.arc(b,c,f,0,Math.PI*2,true);a.fill();a.stroke();e&&this.renderTextAt(false,true,b,c-f-this.e.labelOffset,this.e.label(d))},G:function(a,b,c,d){var e=d.minValue,f=d.maxValue,g=d.unit,h=d.valueFactor;a=this.e.value(a);h=(parseFloat(a)-e)*h;this.e.yAxis||(h+=d.startValue/g);d=c.y-Math.floor(g*h);if(h<0)d=c.y;if(a>f)d=b.y;if(a<e)d=c.y;return d},S:function(a,b,c,d,
e){var f={};f.totalHeight=d.y-c.y;f.cellWidth=Math.round((d.x-c.x)/(!this.e.offset?b.length-1:b.length));var g=!!this.e.yAxis,h=this.e.view.indexOf("stacked")!=-1?this.na(b):this.la();f.maxValue=h.max;f.minValue=h.min;e||this.ia(a,b,c,d,f.minValue,f.maxValue,f.cellWidth);if(g){f.maxValue=parseFloat(this.e.yAxis.end);f.minValue=parseFloat(this.e.yAxis.start)}b=this.P(f.minValue,f.maxValue);a=b[0];f.valueFactor=b[1];f.unit=a?f.totalHeight/a:10;f.startValue=0;if(!g){f.startValue=f.unit>10?f.unit:10;
f.unit=a?(f.totalHeight-f.startValue)/a:10}return f}};
dhtmlx.chart.bar={pvt_render_bar:function(a,b,c,d,e,f){var g,h,j,l,i=d.y-c.y,o=!!this.e.yAxis,n=!!this.e.xAxis;h=this.la();g=h.max;h=h.min;var q=Math.floor((d.x-c.x)/b.length);!e&&!(this.e.origin!="auto"&&!o)&&this.ia(a,b,c,d,h,g,q);if(o){g=parseFloat(this.e.yAxis.end);h=parseFloat(this.e.yAxis.start)}j=this.P(h,g);l=j[0];j=j[1];var z=l?i/l:l;if(!o&&!(this.e.origin!="auto"&&n)){var A=10;z=l?(i-A)/l:A}!e&&this.e.origin!="auto"&&!o&&this.e.origin>h&&this.Ka(a,b,c,d,q,d.y-z*(this.e.origin-h));i=parseInt(this.e.width,
10);if(this.i&&i*this.i.length+4>q)i=q/this.i.length-4;l=Math.floor((q-i*this.i.length)/2);var t=typeof this.e.radius!="undefined"?parseInt(this.e.radius,10):Math.round(i/5),x=false,F=this.e.gradient;if(F&&typeof F!="function"){x=F;F=false}else if(F){F=a.createLinearGradient(0,d.y,0,c.y);this.e.gradient(F)}n||this.m(a,c.x,d.y+0.5,d.x,d.y+0.5,"#000000",1);for(var y=0;y<b.length;y++){var D=parseFloat(this.e.value(b[y]));if(D>g)D=g;D-=h;D*=j;var s=c.x+l+y*q+(i+1)*e,C=d.y;if(D<0||this.e.yAxis&&D===0&&
!(this.e.origin!="auto"&&this.e.origin>h))this.renderTextAt(true,true,s+Math.floor(i/2),C,this.e.label(b[y]));else{if(!o&&!(this.e.origin!="auto"&&n))D+=A/z;var G=F||this.e.color.call(this,b[y]);this.e.border&&this.nb(a,s,C,i,h,t,z,D,G);a.globalAlpha=this.e.alpha.call(this,b[y]);var H=this.mb(a,c,s,C,i,h,t,z,D,G,F,x);a.globalAlpha=1;x&&this.ob(a,s,C,i,h,t,z,D,G,x);H[0]!=s?this.renderTextAt(false,true,s+Math.floor(i/2),H[1],this.e.label(b[y])):this.renderTextAt(true,true,s+Math.floor(i/2),H[3],this.e.label(b[y]));
f.addRect(b[y].id,[s,H[3],H[2],H[1]],e)}}},ea:function(a,b,c,d,e,f,g){var h=this.e.xAxis,j=c;if(h&&this.e.origin!="auto"&&this.e.origin>g){c-=(this.e.origin-g)*e;j=c;d-=this.e.origin-g;if(d<0){d*=-1;a.translate(b+f,c);a.rotate(Math.PI);c=b=0}c-=0.5}return{value:d,x0:b,y0:c,start:j}},mb:function(a,b,c,d,e,f,g,h,j,l,i,o){a.save();a.fillStyle=l;var n=this.ea(a,c,d,j,h,e,f);e=this.$(a,n.x0,n.y0,e,g,h,n.value,this.e.border?1:0);if(i&&!o)a.lineTo(n.x0+(this.e.border?1:0),b.y);a.fill();a.restore();a=n.x0;
b=n.x0!=c?c+e[0]:e[0];d=n.x0!=c?n.start-e[1]:d;c=n.x0!=c?n.start:e[1];return[a,d,b,c]},nb:function(a,b,c,d,e,f,g,h,j){a.save();b=this.ea(a,b,c,h,g,d,e);a.fillStyle=j;this.$(a,b.x0,b.y0,d,f,g,b.value,0);a.lineTo(b.x0,0);a.fill();a.fillStyle="#000000";a.globalAlpha=0.37;this.$(a,b.x0,b.y0,d,f,g,b.value,0);a.fill();a.restore()},ob:function(a,b,c,d,e,f,g,h,j,l){a.save();b=this.ea(a,b,c,h,g,d,e);j=this.Z(a,b.x0,b.y0,b.x0+d,b.y0-g*b.value+2,l,j,"y");a.fillStyle=j.gradient;this.$(a,b.x0+j.offset,b.y0,d-
j.offset*2,f,g,b.value,j.offset);a.fill();a.restore()},$:function(a,b,c,d,e,f,g,h){a.beginPath();var j=0;if(e>f*g){var l=(e-f*g)/e;j=-Math.acos(l)+Math.PI/2}a.moveTo(b+h,c);var i=c-Math.floor(f*g)+e+(e?0:h);e<f*g&&a.lineTo(b+h,i);f=b+e;e&&a.arc(f,i,e-h,-Math.PI+j,-Math.PI/2,false);g=b+d-e-(e?0:h);f=i-e+(e?h:0);a.lineTo(g,f);i=i;e&&a.arc(g,i,e-h,-Math.PI/2,0-j,false);d=b+d-h;a.lineTo(d,c);a.lineTo(b+h,c);return[d,f]}};
dhtmlx.chart.pie={pvt_render_pie:function(a,b,c,d,e,f){this.Za(a,b,c,d,1,f)},Za:function(a,b,c,d,e,f){var g=0,h=this.zb(c,d);c=this.e.radius?this.e.radius:h.radius;this.max(this.e.value);for(var j=[],l=[],i=0,o=0;o<b.length;o++)g+=parseFloat(this.e.value(b[o]));for(o=0;o<b.length;o++){l[o]=parseFloat(this.e.value(b[o]));j[o]=Math.PI*2*(g?(l[o]+i)/g:1/b.length);i+=l[o]}d=this.e.x?this.e.x:h.x;var n=this.e.y?this.e.y:h.y;e==1&&this.e.shadow&&this.hb(a,d,n,c);n/=e;var q=-Math.PI/2;a.scale(1,e);for(o=
0;o<b.length;o++)if(l[o]){a.lineWidth=2;a.beginPath();a.moveTo(d,n);alpha1=-Math.PI/2+j[o]-1.0E-4;a.arc(d,n,c,q,alpha1,false);a.lineTo(d,n);var z=this.e.color.call(this,b[o]);a.fillStyle=z;a.strokeStyle=this.e.lineColor(b[o]);a.stroke();a.fill();this.e.pieInnerText&&this.Ia(d,n,5*c/6,q,alpha1,e,this.e.pieInnerText(b[o],g),true);this.e.label&&this.Ia(d,n,c+this.e.labelOffset,q,alpha1,e,this.e.label(b[o]));if(e!=1){this.Ba(a,d,n,q,alpha1,c,true);a.fillStyle="#000000";a.globalAlpha=0.2;this.Ba(a,d,n,
q,alpha1,c,false);a.globalAlpha=1;a.fillStyle=z}f.addSector(b[o].id,q,alpha1,d,n,c,e);q=alpha1}if(this.e.gradient){b=e!=1?d+c/3:d;f=e!=1?n+c/3:n;this.Wb(a,d,n,c,b,f)}a.scale(1,1/e)},zb:function(a,b){var c=b.x-a.x,d=b.y-a.y;b=a.x+c/2;a=a.y+d/2;c=Math.min(c/2,d/2);return{x:b,y:a,radius:c}},Ba:function(a,b,c,d,e,f,g){a.lineWidth=1;if(d<=0&&e>=0||d>=0&&e<=Math.PI||d<=Math.PI&&e>=Math.PI){if(d<=0&&e>=0){d=0;g=false;this.Ja(a,b,c,f,d,e)}if(d<=Math.PI&&e>=Math.PI){e=Math.PI;g=false;this.Ja(a,b,c,f,d,e)}var h=
(this.e.height||Math.floor(f/4))/this.e.cant;a.beginPath();a.arc(b,c,f,d,e,false);a.lineTo(b+f*Math.cos(e),c+f*Math.sin(e)+h);a.arc(b,c+h,f,e,d,true);a.lineTo(b+f*Math.cos(d),c+f*Math.sin(d));a.fill();g&&a.stroke()}},Ja:function(a,b,c,d,e,f){a.beginPath();a.arc(b,c,d,e,f,false);a.stroke()},hb:function(a,b,c,d){for(var e=["#676767","#7b7b7b","#a0a0a0","#bcbcbc","#d1d1d1","#d6d6d6"],f=e.length-1;f>-1;f--){a.beginPath();a.fillStyle=e[f];a.arc(b+2,c+2,d+f,0,Math.PI*2,true);a.fill()}},yb:function(a){a.addColorStop(0,
"#ffffff");a.addColorStop(0.7,"#7a7a7a");a.addColorStop(1,"#000000");return a},Wb:function(a,b,c,d,e,f){a.globalAlpha=0.3;a.beginPath();var g;if(typeof this.e.gradient!="function"){g=a.createRadialGradient(e,f,d/4,b,c,d);g=this.yb(g)}else g=this.e.gradient(g);a.fillStyle=g;a.arc(b,c,d,0,Math.PI*2,true);a.fill();a.globalAlpha=1},Ia:function(a,b,c,d,e,f,g,h){if(g=this.renderText(0,0,g,0,1)){var j=g.scrollWidth;g.style.width=j+"px";if(j>a)j=a;var l=8;if(h)l=j/1.8;var i=d+(e-d)/2;c-=(l-8)/2;var o=-l,
n=-8,q="left";if(i>=Math.PI/2&&i<Math.PI){o=-j-o+1;q="right"}if(i<=3*Math.PI/2&&i>=Math.PI){o=-j-o+1;q="right"}d=(b+Math.floor(c*Math.sin(i)))*f+n;l=a+Math.floor((c+l/2)*Math.cos(i))+o;var z=e<Math.PI/2+0.01,A=i<Math.PI/2;if(A&&z)l=Math.max(l,a+3);else if(!A&&!z)l=Math.min(l,a-j);if(!h&&f<1&&d>b*f)d+=this.e.height||Math.floor(c/4);g.style.top=d+"px";g.style.left=l+"px";g.style.width=j+"px";g.style.textAlign=q;g.style.whiteSpace="nowrap"}}};
dhtmlx.chart.pie3D={pvt_render_pie3D:function(a,b,c,d,e,f){this.Za(a,b,c,d,this.e.cant,f)}};
dhtmlx.Group={j:function(){this.data.attachEvent("onStoreLoad",dhtmlx.bind(function(){this.e.group&&this.group(this.e.group,false)},this));this.attachEvent("onBeforeRender",dhtmlx.bind(function(a){if(this.e.sort){a.block();a.sort(this.e.sort);a.unblock()}},this));this.attachEvent("onBeforeSort",dhtmlx.bind(function(){this.e.sort=null},this))},Cb:function(a,b){a.attachEvent("onClearAll",dhtmlx.bind(function(){this.ungroup(false)},b))},sum:function(a,b){a=dhtmlx.Template.setter(0,a);b=b||this.data;
var c=0;b.each(function(d){c+=a(d)*1});return c},min:function(a,b){a=dhtmlx.Template.setter(0,a);b=b||this.data;var c=Infinity;b.each(function(d){if(a(d)*1<c)c=a(d)*1});return c*1},max:function(a,b){a=dhtmlx.Template.setter(0,a);b=b||this.data;var c=-Infinity;b.each(function(d){if(a(d)*1>c)c=a(d)*1});return c},Xb:function(a){var b=function(j,l){j=dhtmlx.Template.setter(0,j);return j(l[0])},c=dhtmlx.Template.setter(0,a.by);a.map[c]||(a.map[c]=[c,b]);var d={},e=[];this.data.each(function(j){var l=c(j);
if(!d[l]){e.push({id:l});d[l]=dhtmlx.toArray()}d[l].push(j)});for(var f in a.map){var g=a.map[f][1]||b;if(typeof g!="function")g=this[g];for(var h=0;h<e.length;h++)e[h][f]=g.call(this,a.map[f][0],d[e[h].id])}this.Va=this.data;this.data=new dhtmlx.DataStore;this.data.provideApi(this,true);this.Cb(this.data,this);this.parse(e,"json")},group:function(a,b){this.ungroup(false);this.Xb(a);b!==false&&this.render()},ungroup:function(a){if(this.Va){this.data=this.Va;this.data.provideApi(this,true)}a!==false&&
this.render()},group_setter:function(a,b){return b},sort_setter:function(a,b){if(typeof b!="object")b={by:b};this.D(b,{as:"string",dir:"asc"});return b}};dhtmlx.DataDriver.dhtmlxgrid={Bb:"_get_cell_value",toObject:function(a){return this.Na=a},getRecords:function(a){return a.rowsBuffer},getDetails:function(a){for(var b={},c=0;c<this.Na.getColumnsNum();c++)b["data"+c]=this.Na[this.Bb](a,c);return b},getInfo:function(){return{L:0,B:0}}};
dhtmlx.Canvas={j:function(){this.T=[]},Qb:function(a){this.p=dhtmlx.html.create("canvas",{width:a.offsetWidth,height:a.offsetHeight});a.appendChild(this.p);if(!this.p.getContext)if(dhtmlx.H){dhtmlx.require("thirdparty/excanvas/excanvas.js");G_vmlCanvasManager.init_(document);G_vmlCanvasManager.initElement(this.p)}return this.p},getCanvas:function(a){return(this.p||this.Qb(this.g)).getContext(a||"2d")},Tb:function(){if(this.p){this.p.setAttribute("width",this.p.parentNode.offsetWidth);this.p.setAttribute("height",
this.p.parentNode.offsetHeight)}},renderText:function(a,b,c,d,e){if(c){a=dhtmlx.html.create("DIV",{"class":"dhx_canvas_text"+(d?" "+d:""),style:"left:"+a+"px; top:"+b+"px;"},c);this.g.appendChild(a);this.T.push(a);if(e)a.style.width=e+"px";return a}},renderTextAt:function(a,b,c,d,e,f,g){if(e=this.renderText.call(this,c,d,e,f,g)){if(a)e.style.top=a=="middle"?parseInt(d-e.offsetHeight/2,10)+"px":d-e.offsetHeight+"px";if(b)e.style.left=b=="left"?c-e.offsetWidth+"px":parseInt(c-e.offsetWidth/2,10)+"px"}return e},
clearCanvas:function(){for(var a=0;a<this.T.length;a++)this.g.removeChild(this.T[a]);this.T=[];if(this.g.k){this.g.k.parentNode.removeChild(this.g.k);this.g.k=null}this.getCanvas().clearRect(0,0,this.p.offsetWidth,this.p.offsetHeight)}};
dhtmlXChart=function(a){this.name="Chart";this.version="3.0";dhtmlx.extend(this,dhtmlx.Settings);this.qa(a,"dhx_chart");dhtmlx.extend(this,dhtmlx.DataLoader);this.data.provideApi(this,true);dhtmlx.extend(this,dhtmlx.EventSystem);dhtmlx.extend(this,dhtmlx.MouseEvents);dhtmlx.extend(this,dhtmlx.Destruction);dhtmlx.extend(this,dhtmlx.Canvas);dhtmlx.extend(this,dhtmlx.Group);dhtmlx.extend(this,dhtmlx.AutoTooltip);for(var b in dhtmlx.chart)dhtmlx.extend(this,dhtmlx.chart[b]);this.K(a,{color:"RAINBOW",
alpha:"1",label:false,value:"{obj.value}",padding:{},view:"pie",lineColor:"#ffffff",cant:0.5,width:15,labelWidth:100,line:{},item:{},shadow:true,gradient:false,border:true,labelOffset:20,origin:"auto"});this.i=[this.e];this.data.attachEvent("onStoreUpdated",dhtmlx.bind(function(){this.render()},this));this.attachEvent("onLocateData",this.Yb)};
dhtmlXChart.prototype={r:"dhx_area_id",on_click:{},on_dblclick:{},on_mouse_move:{},resize:function(){this.Tb();this.render()},view_setter:function(a,b){if(typeof this.e.offset=="undefined")this.e.offset=b=="area"||b=="stackedArea"?false:true;return b},render:function(){if(this.callEvent("onBeforeRender",[this.data])){this.clearCanvas();this.e.legend&&this.rb(this.getCanvas(),this.data.getRange(),this.g.offsetWidth,this.g.offsetHeight);for(var a=this.xb(this.g.offsetWidth,this.g.offsetHeight),b=new dhtmlx.ui.Map(this.r),
c=this.e,d=0;d<this.i.length;d++){this.e=this.i[d];this["pvt_render_"+this.e.view](this.getCanvas(),this.data.getRange(),a.start,a.end,d,b)}b.render(this.g);this.e=c}},value_setter:dhtmlx.Template.obj_setter,alpha_setter:dhtmlx.Template.obj_setter,label_setter:dhtmlx.Template.obj_setter,lineColor_setter:dhtmlx.Template.obj_setter,pieInnerText_setter:dhtmlx.Template.obj_setter,gradient_setter:function(a,b){if(typeof b!="function"&&b&&(b===true||b!="3d"))b="light";return b},colormap:{RAINBOW:function(a){a=
Math.floor(this.indexById(a.id)/this.dataCount()*1536);if(a==1536)a-=1;return this.Rb[Math.floor(a/256)](a%256)}},color_setter:function(a,b){return this.colormap[b]||dhtmlx.Template.obj_setter(a,b)},legend_setter:function(a,b){if(typeof b!="object")b={template:b};this.D(b,{width:150,height:18,layout:"y",align:"left",valign:"bottom",template:"",marker:{type:"square",width:25,height:15}});b.template=dhtmlx.Template.setter(0,b.template);return b},item_setter:function(a,b){if(typeof b!="object")b={color:b,
borderColor:b};this.D(b,{radius:4,color:"#000000",borderColor:"#000000",borderWidth:2});b.color=dhtmlx.Template.setter(0,b.color);b.borderColor=dhtmlx.Template.setter(0,b.borderColor);return b},line_setter:function(a,b){if(typeof b!="object")b={color:b};this.D(b,{width:3,color:"#d4d4d4"});b.color=dhtmlx.Template.setter(0,b.color);return b},padding_setter:function(a,b){if(typeof b!="object")b={left:b,right:b,top:b,bottom:b};this.D(b,{left:50,right:20,top:35,bottom:40});return b},xAxis_setter:function(a,
b){if(!b)return false;if(typeof b!="object")b={template:b};this.D(b,{title:"",color:"#000000",template:"{obj}",lines:false});if(b.template)b.template=dhtmlx.Template.setter(0,b.template);return b},yAxis_setter:function(a,b){this.D(b,{title:"",color:"#000000",template:"{obj}",lines:true});if(b.template)b.template=dhtmlx.Template.setter(0,b.template);return b},ia:function(a,b,c,d,e,f,g){e=this.vb(a,b,c,d,e,f);this.Ka(a,b,c,d,g,e);return e},Ka:function(a,b,c,d,e,f){if(this.e.xAxis){var g=c.x-0.5;f=parseInt(f?
f:d.y,10)+0.5;var h=d.x,j,l=true;this.m(a,g,f,h,f,this.e.xAxis.color,1);for(var i=0;i<b.length;i++){if(this.e.offset===true)j=g+e/2+i*e;else{j=g+i*e;l=!!i}var o=this.e.origin!="auto"&&this.e.view=="bar"&&parseFloat(this.e.value(b[i]))<this.e.origin;this.tb(j,f,b[i],l,o);this.e.view_setter!="bar"&&this.ub(a,j,d.y,c.y)}this.renderTextAt(true,false,g,d.y+this.e.padding.bottom-3,this.e.xAxis.title,"dhx_axis_title_x",d.x-c.x);this.e.xAxis.lines&&this.e.offset&&this.m(a,h+0.5,d.y,h+0.5,c.y+0.5,this.e.xAxis.color,
0.2)}},vb:function(a,b,c,d,e,f){var g;b={};if(this.e.yAxis){var h=c.x-0.5,j=d.y,l=c.y,i=d.y;this.m(a,h,j,h,l,this.e.yAxis.color,1);if(this.e.yAxis.step)g=parseFloat(this.e.yAxis.step);if(typeof this.e.yAxis.step=="undefined"||typeof this.e.yAxis.start=="undefined"||typeof this.e.yAxis.end=="undefined"){b=this.za(e,f);e=b.start;f=b.end;g=b.step;this.e.yAxis.end=f;this.e.yAxis.start=e}if(g!==0){l=(j-l)*g/(f-e);for(var o=0,n=e;n<=f;n+=g){if(b.fixNum)n=parseFloat((new Number(n)).toFixed(b.fixNum));var q=
Math.floor(j-o*l)+0.5;!(n==e&&this.e.origin=="auto")&&this.e.yAxis.lines&&this.m(a,h,q,d.x,q,this.e.yAxis.color,0.2);if(n==this.e.origin)i=q;this.renderText(0,q-5,this.e.yAxis.template(n.toString()),"dhx_axis_item_y",c.x-5);o++}this.ab(c,d);return i}}},ab:function(a,b){if(a=this.renderTextAt("middle",false,0,parseInt((b.y-a.y)/2+a.y,10),this.e.yAxis.title,"dhx_axis_title_y"))a.style.left=(dhtmlx.env.transform?(a.offsetHeight-a.offsetWidth)/2:0)+"px"},za:function(a,b){if(this.e.origin!="auto"&&this.e.origin<
a)a=this.e.origin;var c,d,e;c=(b-a)/8||1;var f=Math.floor(this.Sa(c)),g=Math.pow(10,f),h=c/g;h=h>5?10:5;c=parseInt(h,10)*g;if(c>Math.abs(a))d=a<0?-c:0;else{var j=Math.abs(a),l=Math.floor(this.Sa(j)),i=j/Math.pow(10,l);d=Math.ceil(i*10)/10*Math.pow(10,l)-c;if(a<0)d=-d-2*c}for(e=d;e<b;){e+=c;e=parseFloat((new Number(e)).toFixed(Math.abs(f)))}return{start:d,end:e,step:c,fixNum:Math.abs(f)}},la:function(a){var b,c;if((c=arguments.length&&a=="h"?this.e.xAxis:this.e.yAxis)&&typeof c.end!="undefied"&&typeof c.start!=
"undefied"&&c.step){b=parseFloat(c.end);c=parseFloat(c.start)}else{b=this.max(this.i[0].value);c=this.min(this.i[0].value);if(this.i.length>1)for(var d=1;d<this.i.length;d++){var e=this.max(this.i[d].value),f=this.min(this.i[d].value);if(e>b)b=e;if(f<c)c=f}}return{max:b,min:c}},Sa:function(a){var b="log";return Math.floor(Math[b](a)/Math.LN10)},tb:function(a,b,c,d,e){this.e.xAxis&&this.renderTextAt(e,d,a,b,this.e.xAxis.template(c))},ub:function(a,b,c,d){this.e.xAxis&&this.e.xAxis.lines&&this.m(a,
b,c,b,d,this.e.xAxis.color,0.2)},m:function(a,b,c,d,e,f,g){a.strokeStyle=f;a.lineWidth=g;a.beginPath();a.moveTo(b,c);a.lineTo(d,e);a.stroke()},P:function(a,b){var c=1;if(b!=a){a=b-a;if(Math.abs(a)<1)for(;Math.abs(a)<1;){c*=10;a*=c}}else a=a;return[a,c]},Rb:[function(a){return"#FF"+dhtmlx.math.toHex(a/2,2)+"00"},function(a){return"#FF"+dhtmlx.math.toHex(a/2+128,2)+"00"},function(a){return"#"+dhtmlx.math.toHex(255-a,2)+"FF00"},function(a){return"#00FF"+dhtmlx.math.toHex(a,2)},function(a){return"#00"+
dhtmlx.math.toHex(255-a,2)+"FF"},function(a){return"#"+dhtmlx.math.toHex(a,2)+"00FF"}],addSeries:function(a){var b=this.e;this.e=dhtmlx.extend({},b);this.K(a,{});this.i.push(this.e);this.e=b},Yb:function(a,b){this.gb=b.getAttribute("userdata");for(a=0;a<this.i.length;a++){var c=this.i[a].tooltip;c&&c.disable()}(c=this.i[this.gb].tooltip)&&c.enable()},rb:function(a,b){var c=0,d=0,e=this.e.legend,f,g,h=this.e.legend.layout!="x"?"width:"+e.width+"px":"",j=dhtmlx.html.create("DIV",{"class":"dhx_chart_legend",
style:"left:"+c+"px; top:"+d+"px;"+h},"");this.g.appendChild(j);var l=[];if(e.values)for(h=0;h<e.values.length;h++)l.push(this.Ha(j,e.values[h].text));else for(h=0;h<b.length;h++)l.push(this.Ha(j,e.template(b[h])));g=j.offsetWidth;f=j.offsetHeight;this.e.legend.width=g;this.e.legend.height=f;if(g<this.g.offsetWidth){if(e.layout=="x"&&e.align=="center")c=(this.g.offsetWidth-g)/2;if(e.align=="right")c=this.g.offsetWidth-g}if(f<this.g.offsetHeight)if(e.valign=="middle"&&e.align!="center"&&e.layout!=
"x")d=(this.g.offsetHeight-f)/2;else if(e.valign=="bottom")d=this.g.offsetHeight-f;j.style.left=c+"px";j.style.top=d+"px";for(h=0;h<l.length;h++){var i=l[h],o=e.values?e.values[h].color:this.e.color.call(this,b[h]);this.sb(a,i.offsetLeft+c,i.offsetTop+d,o)}l=null},Ha:function(a,b){var c="";if(this.e.legend.layout=="x")c="float:left;";b=dhtmlx.html.create("DIV",{style:c+"padding-left:"+(10+this.e.legend.marker.width)+"px","class":"dhx_chart_legend_item"},b);a.appendChild(b);return b},sb:function(a,
b,c,d){var e=this.e.legend;a.strokeStyle=a.fillStyle=d;a.lineWidth=e.marker.height;a.lineCap=e.marker.type;a.beginPath();b+=a.lineWidth/2+5;c+=a.lineWidth/2+3;a.moveTo(b,c);b=b+e.marker.width-e.marker.height+1;a.lineTo(b,c);a.stroke()},xb:function(a,b){var c,d,e,f;c=this.e.padding.left;d=this.e.padding.top;e=a-this.e.padding.right;f=b-this.e.padding.bottom;if(this.e.legend){a=this.e.legend;b=this.e.legend.width;var g=this.e.legend.height;if(a.layout=="x")if(a.valign=="center")if(a.align=="right")e-=
b;else{if(a.align=="left")c+=b}else if(a.valign=="bottom")f-=g;else d+=g;else if(a.align=="right")e-=b;else if(a.align=="left")c+=b}return{start:{x:c,y:d},end:{x:e,y:f}}},na:function(a){var b,c;if(this.e.yAxis&&typeof this.e.yAxis.end!="undefied"&&typeof this.e.yAxis.start!="undefied"&&this.e.yAxis.step){b=parseFloat(this.e.yAxis.end);c=parseFloat(this.e.yAxis.start)}else{for(var d=0;d<a.length;d++){a[d].$sum=0;a[d].$min=Infinity;for(b=0;b<this.i.length;b++){c=parseFloat(this.i[b].value(a[d]));if(!isNaN(c)){a[d].$sum+=
c;if(c<a[d].$min)a[d].$min=c}}}b=-Infinity;c=Infinity;for(d=0;d<a.length;d++){if(a[d].$sum>b)b=a[d].$sum;if(a[d].$min<c)c=a[d].$min}if(c>0)c=0}return{max:b,min:c}},Z:function(a,b,c,d,e,f,g,h){if(f=="light"){a=h=="x"?a.createLinearGradient(b,c,d,c):a.createLinearGradient(b,c,b,e);a.addColorStop(0,"#FFFFFF");a.addColorStop(0.9,g);a.addColorStop(1,g);g=2}else{a.globalAlpha=0.37;g=0;a=h=="x"?a.createLinearGradient(b,e,b,c):a.createLinearGradient(b,c,d,c);a.addColorStop(0,"#000000");a.addColorStop(0.5,
"#FFFFFF");a.addColorStop(0.6,"#FFFFFF");a.addColorStop(1,"#000000")}return{gradient:a,offset:g}}};dhtmlx.compat("layout");
document.createElement("canvas").getContext||function(){function a(){return this.context_||(this.context_=new l(this))}function b(k,m){var p=G.call(arguments,2);return function(){return k.apply(m,p.concat(G.call(arguments)))}}function c(k){var m=k.srcElement;switch(k.propertyName){case "width":m.style.width=m.attributes.width.nodeValue+"px";m.getContext().clearRect();break;case "height":m.style.height=m.attributes.height.nodeValue+"px";m.getContext().clearRect();break}}function d(k){k=k.srcElement;
if(k.firstChild){k.firstChild.style.width=k.clientWidth+"px";k.firstChild.style.height=k.clientHeight+"px"}}function e(){return[[1,0,0],[0,1,0],[0,0,1]]}function f(k,m){for(var p=e(),r=0;r<3;r++)for(var u=0;u<3;u++){for(var w=0,B=0;B<3;B++)w+=k[r][B]*m[B][u];p[r][u]=w}return p}function g(k,m){m.fillStyle=k.fillStyle;m.lineCap=k.lineCap;m.lineJoin=k.lineJoin;m.lineWidth=k.lineWidth;m.miterLimit=k.miterLimit;m.shadowBlur=k.shadowBlur;m.shadowColor=k.shadowColor;m.shadowOffsetX=k.shadowOffsetX;m.shadowOffsetY=
k.shadowOffsetY;m.strokeStyle=k.strokeStyle;m.globalAlpha=k.globalAlpha;m.arcScaleX_=k.arcScaleX_;m.arcScaleY_=k.arcScaleY_;m.lineScale_=k.lineScale_}function h(k){var m,p=1;k=String(k);if(k.substring(0,3)=="rgb"){m=k.indexOf("(",3);var r=k.indexOf(")",m+1),u=k.substring(m+1,r).split(",");m="#";for(r=0;r<3;r++)m+=S[Number(u[r])];if(u.length==4&&k.substr(3,1)=="a")p=u[3]}else m=k;return{color:m,alpha:p}}function j(k){switch(k){case "butt":return"flat";case "round":return"round";case "square":default:return"square"}}
function l(k){this.m_=e();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=s*1;this.globalAlpha=1;this.canvas=k;var m=k.ownerDocument.createElement("div");m.style.width=k.clientWidth+"px";m.style.height=k.clientHeight+"px";m.style.overflow="hidden";m.style.position="absolute";k.appendChild(m);this.element_=m;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function i(k,m,p,r){k.currentPath_.push({type:"bezierCurveTo",
cp1x:m.x,cp1y:m.y,cp2x:p.x,cp2y:p.y,x:r.x,y:r.y});k.currentX_=r.x;k.currentY_=r.y}function o(k){for(var m=0;m<3;m++)for(var p=0;p<2;p++)if(!isFinite(k[m][p])||isNaN(k[m][p]))return false;return true}function n(k,m,p){if(o(m)){k.m_=m;if(p){var r=m[0][0]*m[1][1]-m[0][1]*m[1][0];k.lineScale_=D(y(r))}}}function q(k){this.type_=k;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function z(){}var A=Math,t=A.round,x=A.sin,F=A.cos,y=A.abs,D=A.sqrt,s=10,C=s/2,G=Array.prototype.slice,
H={init:function(k){if(/MSIE/.test(navigator.userAgent)&&!window.opera){var m=k||document;m.createElement("canvas");m.attachEvent("onreadystatechange",b(this.init_,this,m))}},init_:function(k){k.namespaces.g_vml_||k.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");k.namespaces.g_o_||k.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");if(!k.styleSheets.ex_canvas_){var m=k.createStyleSheet();m.owningElement.id="ex_canvas_";m.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}g_vml_\\:*{behavior:url(#default#VML)}g_o_\\:*{behavior:url(#default#VML)}"}var p=
k.getElementsByTagName("canvas");for(k=0;k<p.length;k++)this.initElement(p[k])},initElement:function(k){if(!k.getContext){k.getContext=a;k.innerHTML="";k.attachEvent("onpropertychange",c);k.attachEvent("onresize",d);var m=k.attributes;if(m.width&&m.width.specified)k.style.width=m.width.nodeValue+"px";else k.width=k.clientWidth;if(m.height&&m.height.specified)k.style.height=m.height.nodeValue+"px";else k.height=k.clientHeight}return k}};H.init();for(var S=[],M=0;M<16;M++)for(var P=0;P<16;P++)S[M*16+
P]=M.toString(16)+P.toString(16);var E=l.prototype;E.clearRect=function(){this.element_.innerHTML=""};E.beginPath=function(){this.currentPath_=[]};E.moveTo=function(k,m){var p=this.getCoords_(k,m);this.currentPath_.push({type:"moveTo",x:p.x,y:p.y});this.currentX_=p.x;this.currentY_=p.y};E.lineTo=function(k,m){k=this.getCoords_(k,m);this.currentPath_.push({type:"lineTo",x:k.x,y:k.y});this.currentX_=k.x;this.currentY_=k.y};E.bezierCurveTo=function(k,m,p,r,u,w){u=this.getCoords_(u,w);w=this.getCoords_(k,
m);var B=this.getCoords_(p,r);i(this,w,B,u)};E.quadraticCurveTo=function(k,m,p,r){var u=this.getCoords_(k,m);p=this.getCoords_(p,r);r={x:this.currentX_+2/3*(u.x-this.currentX_),y:this.currentY_+2/3*(u.y-this.currentY_)};var w={x:r.x+(p.x-this.currentX_)/3,y:r.y+(p.y-this.currentY_)/3};i(this,r,w,p)};E.arc=function(k,m,p,r,u,w){p*=s;var B=w?"at":"wa",v=k+F(r)*p-C,Q=m+x(r)*p-C,J=k+F(u)*p-C,N=m+x(u)*p-C;if(v==J&&!w)v+=0.125;k=this.getCoords_(k,m);var K=this.getCoords_(v,Q),L=this.getCoords_(J,N);this.currentPath_.push({type:B,
x:k.x,y:k.y,radius:p,xStart:K.x,yStart:K.y,xEnd:L.x,yEnd:L.y})};E.rect=function(k,m,p,r){this.moveTo(k,m);this.lineTo(k+p,m);this.lineTo(k+p,m+r);this.lineTo(k,m+r);this.closePath()};E.strokeRect=function(k,m,p,r){var u=this.currentPath_;this.beginPath();this.moveTo(k,m);this.lineTo(k+p,m);this.lineTo(k+p,m+r);this.lineTo(k,m+r);this.closePath();this.stroke();this.currentPath_=u};E.fillRect=function(k,m,p,r){var u=this.currentPath_;this.beginPath();this.moveTo(k,m);this.lineTo(k+p,m);this.lineTo(k+
p,m+r);this.lineTo(k,m+r);this.closePath();this.fill();this.currentPath_=u};E.createLinearGradient=function(k,m,p,r){var u=new q("gradient");u.x0_=k;u.y0_=m;u.x1_=p;u.y1_=r;return u};E.createRadialGradient=function(k,m,p,r,u,w){var B=new q("gradientradial");B.x0_=k;B.y0_=m;B.r0_=p;B.x1_=r;B.y1_=u;B.r1_=w;return B};E.drawImage=function(k){var m,p,r,u,w,B,v,Q,J=k.runtimeStyle.width,N=k.runtimeStyle.height;k.runtimeStyle.width="auto";k.runtimeStyle.height="auto";var K=k.width,L=k.height;k.runtimeStyle.width=
J;k.runtimeStyle.height=N;if(arguments.length==3){m=arguments[1];p=arguments[2];w=B=0;v=r=K;Q=u=L}else if(arguments.length==5){m=arguments[1];p=arguments[2];r=arguments[3];u=arguments[4];w=B=0;v=K;Q=L}else if(arguments.length==9){w=arguments[1];B=arguments[2];v=arguments[3];Q=arguments[4];m=arguments[5];p=arguments[6];r=arguments[7];u=arguments[8]}else throw Error("Invalid number of arguments");var I=this.getCoords_(m,p),R=[],T=10,O=10;R.push(" <g_vml_:group",' coordsize="',s*T,",",s*O,'"',' coordorigin="0,0"',
' style="width:',T,"px;height:",O,"px;position:absolute;");if(this.m_[0][0]!=1||this.m_[0][1]){var U=[];U.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",t(I.x/s),",","Dy=",t(I.y/s),"");I=I;var V=this.getCoords_(m+r,p),W=this.getCoords_(m,p+u),X=this.getCoords_(m+r,p+u);I.x=A.max(I.x,V.x,W.x,X.x);I.y=A.max(I.y,V.y,W.y,X.y);R.push("padding:0 ",t(I.x/s),"px ",t(I.y/s),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",U.join(""),", sizingmethod='clip');")}else R.push("top:",
t(I.y/s),"px;left:",t(I.x/s),"px;");R.push(' ">','<g_vml_:image src="',k.src,'"',' style="width:',s*r,"px;"," height:",s*u,'px;"',' cropleft="',w/K,'"',' croptop="',B/L,'"',' cropright="',(K-w-v)/K,'"',' cropbottom="',(L-B-Q)/L,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",R.join(""))};E.stroke=function(k){var m=[],p=h(k?this.fillStyle:this.strokeStyle),r=p.color,u=p.alpha*this.globalAlpha,w=p=10;m.push("<g_vml_:shape",' filled="',!!k,'"',' style="position:absolute;width:',
p,"px;height:",w,'px;"',' coordorigin="0 0" coordsize="',s*p," ",s*w,'"',' stroked="',!k,'"',' path="');p={x:null,y:null};w={x:null,y:null};for(var B=0;B<this.currentPath_.length;B++){var v=this.currentPath_[B],Q;switch(v.type){case "moveTo":Q=v;m.push(" m ",t(v.x),",",t(v.y));break;case "lineTo":m.push(" l ",t(v.x),",",t(v.y));break;case "close":m.push(" x ");v=null;break;case "bezierCurveTo":m.push(" c ",t(v.cp1x),",",t(v.cp1y),",",t(v.cp2x),",",t(v.cp2y),",",t(v.x),",",t(v.y));break;case "at":case "wa":m.push(" ",
v.type," ",t(v.x-this.arcScaleX_*v.radius),",",t(v.y-this.arcScaleY_*v.radius)," ",t(v.x+this.arcScaleX_*v.radius),",",t(v.y+this.arcScaleY_*v.radius)," ",t(v.xStart),",",t(v.yStart)," ",t(v.xEnd),",",t(v.yEnd));break}if(v){if(p.x==null||v.x<p.x)p.x=v.x;if(w.x==null||v.x>w.x)w.x=v.x;if(p.y==null||v.y<p.y)p.y=v.y;if(w.y==null||v.y>w.y)w.y=v.y}}m.push(' ">');if(k)if(typeof this.fillStyle=="object"){var J=this.fillStyle,N=0,K={x:0,y:0};r=0;var L=1;if(J.type_=="gradient"){p=J.x0_/this.arcScaleX_;w=J.y0_/
this.arcScaleY_;B=J.x1_/this.arcScaleX_;v=J.y1_/this.arcScaleY_;var I=this.getCoords_(p,w),R=this.getCoords_(B,v);p=R.x-I.x;w=R.y-I.y;N=Math.atan2(p,w)*180/Math.PI;if(N<0)N+=360;if(N<1.0E-6)N=0}else{I=this.getCoords_(J.x0_,J.y0_);r=w.x-p.x;w=w.y-p.y;K={x:(I.x-p.x)/r,y:(I.y-p.y)/w};r/=this.arcScaleX_*s;w/=this.arcScaleY_*s;var T=A.max(r,w);r=2*J.r0_/T;L=2*J.r1_/T-r}var O=J.colors_;O.sort(function(aa,ba){return aa.offset-ba.offset});p=O.length;var U=O[0].color,V=O[p-1].color,W=O[0].alpha*this.globalAlpha,
X=O[p-1].alpha*this.globalAlpha,Z=[];for(B=0;B<p;B++){var $=O[B];Z.push($.offset*L+r+" "+$.color)}m.push('<g_vml_:fill type="',J.type_,'"',' method="none" focus="100%"',' color="',U,'"',' color2="',V,'"',' colors="',Z.join(","),'"',' opacity="',X,'"',' g_o_:opacity2="',W,'"',' angle="',N,'"',' focusposition="',K.x,",",K.y,'" />')}else m.push('<g_vml_:fill color="',r,'" opacity="',u,'" />');else{var Y=this.lineScale_*this.lineWidth;if(Y<1)u*=Y;m.push("<g_vml_:stroke",' opacity="',u,'"',' joinstyle="',
this.lineJoin,'"',' miterlimit="',this.miterLimit,'"',' endcap="',j(this.lineCap),'"',' weight="',Y,'px"',' color="',r,'" />')}m.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",m.join(""))};E.fill=function(){this.stroke(true)};E.closePath=function(){this.currentPath_.push({type:"close"})};E.getCoords_=function(k,m){var p=this.m_;return{x:s*(k*p[0][0]+m*p[1][0]+p[2][0])-C,y:s*(k*p[0][1]+m*p[1][1]+p[2][1])-C}};E.save=function(){var k={};g(this,k);this.aStack_.push(k);this.mStack_.push(this.m_);
this.m_=f(e(),this.m_)};E.restore=function(){g(this.aStack_.pop(),this);this.m_=this.mStack_.pop()};E.translate=function(k,m){k=[[1,0,0],[0,1,0],[k,m,1]];n(this,f(k,this.m_),false)};E.rotate=function(k){var m=F(k),p=x(k);m=[[m,p,0],[-p,m,0],[0,0,1]];n(this,f(m,this.m_),false)};E.scale=function(k,m){this.arcScaleX_*=k;this.arcScaleY_*=m;k=[[k,0,0],[0,m,0],[0,0,1]];n(this,f(k,this.m_),true)};E.transform=function(k,m,p,r,u,w){u=[[k,m,0],[p,r,0],[u,w,1]];n(this,f(u,this.m_),true)};E.setTransform=function(k,
m,p,r,u,w){k=[[k,m,0],[p,r,0],[u,w,1]];n(this,k,true)};E.clip=function(){};E.arcTo=function(){};E.createPattern=function(){return new z};q.prototype.addColorStop=function(k,m){m=h(m);this.colors_.push({offset:k,color:m.color,alpha:m.alpha})};G_vmlCanvasManager=H;CanvasRenderingContext2D=l;CanvasGradient=q;CanvasPattern=z}();if(dhtmlx&&dhtmlx.X)dhtmlx.X["thirdparty/excanvas/excanvas.js"]=true;
